### PR TITLE
Submitting a new Web Part | React-Video-Banner

### PR DESCRIPTION
**Pull request by derhallim**
Type:  New sample

## What's in this Pull Request?
A new Web Part sample, named: react-video-banner. Allows users to add a video as a banner to their sites while controlling text that appears on top of the video.

### CODE REVIEW

**Comment by derhallim** [comment]
A new Web Part sample, named: react-video-banner. Allows users to add a video as a banner to their sites while controlling text that appears on top of the video.

**Comment by hugoabernier** [comment]
Thank you @derhallim. I'm sure people will want to use this sample in their tenants!

Would you be interested in presenting a 10-13 minute demo of this solution on our May 6th SPFx call?

Also, we'd like to start giving the opportunity for contributors to write blog posts describing their solutions. The blog post would appear at aka.ms/m365pnp/community/blog. Would you be interested in writing such a post?

Feel free to DM me if you need more information.

**Comment by derhallim** [comment]
Hi @hugoabernier, thank you for approving the web part, am glad you liked it! 

Yes I can do the presentation and write a blog post about it as well!

**Comment by hugoabernier** [comment]
Great! I have you confirmed on the May 6th agenda. I look forward to your demo!

**Pull request merged**
