### PR TITLE
New sample React-Cherry-Picked-Content

### PR DESCRIPTION
**Pull request by PathToSharePoint**
> By submitting this pull request, you agree to the [contribution guidelines](https://github.com/pnp/sp-dev-fx-webparts/blob/main/CONTRIBUTING.md)

> If you aren't familiar with how to contribute to open-source repositories using GitHub, or if you find the instructions on this page confusing, [sign up](https://forms.office.com/Pages/ResponsePage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUREZVRDVYUUJLT1VNRDM4SjhGMlpUNzBORy4u) for one of our [Sharing is Caring](https://pnp.github.io/sharing-is-caring/#pnp-sic-events) events. It's completely free, and we'll guide you through the process.

|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                            |
| New feature?    | no                              |
| New sample?     | yes                               |
| Related issues? | fixes partially #2228 |

## What's in this Pull Request?

New sample **react-cherry-picked-content**. This is a modern take on the Content Editor Web Part, where code can only be picked from pre-selected libraries (inspired by @mikezimm 's idea #2228).

Featured in the sample:

- Cascading dropdown and conditional display in the Property Pane
- Use of SPHttpClient and the SharePoint REST API to query SharePoint content
- React function component with useState and useEffect hooks
- React Portal in combination with an iframe
- Various examples of client-side code in the samples: Microsoft Graph (teams), Microsoft Graph Toolkit (people, email, agenda), charts (Chart.js, Chartist), widgets (map, stock, countdown, clock, video, game), SharePoint SOAP and REST APIs.

### CODE REVIEW

**Comment by PathToSharePoint** [comment]
I tried to submit a second sample to sp-dev-fx-webparts, but the commits were added to this submission  without letting me fill out a second form. Here  is the info on the second sample:

## What's in this Pull Request?

- New sample **react-cherry-picked-content**. This is a modern take on the Content Editor Web Part, where code can only be picked from pre-selected libraries (inspired by @mikezimm 's idea #2228).
- New sample **react-ppp-pnp-controls**:. The sample showcases the use of the [Property Pane Portal](https://www.npmjs.com/package/property-pane-portal) to display the [PnP SPFx React controls](https://github.com/pnp/sp-dev-fx-controls-react) (version 3.7.0) in the SPFx Property Pane.

Featured in the first sample:

- Cascading dropdown and conditional display in the Property Pane
- Use of SPHttpClient and the SharePoint REST API to query SharePoint content
- React function component with useState and useEffect hooks
- React Portal in combination with an iframe
- Various examples of client-side code in the samples: Microsoft Graph (teams), Microsoft Graph Toolkit (people, email, agenda), charts (Chart.js, Chartist), widgets (map, stock, countdown, clock, video, game), SharePoint SOAP and REST APIs.

Featured in the second sample:

- The PropertyPaneHost function, which creates placeholders in the Property Pane
- The PropertyPanePortal component, which leverages React Portals to teleport React components to the Property Pane.
- Location Picker
- People Picker
- List Picker and List Item Picker (cascading selection)

**Comment by hugoabernier** [comment]
Thank you @PathToSharePoint!

Would you be interested in presenting either of these solutions on the June 16th community call?

You would have 10-13 minutes to demo the web part and the most relevant code areas.

Also, we'd love for you to write a short blog post on the new PnP blog! If you're interested, follow the instructions on the [contribution guide](https://github.com/pnp/blog/blob/main/CONTRIBUTING.md).

**Comment by PathToSharePoint** [comment]
@hugoabernier Thanks for taking some of your Sunday time to publish the samples!

I believe @LuiseFreese already scheduled me to present the Property Pane Portal on 4/7, could you confirm?

As for the blog post, let me see if I find something interesting to say :-)

**Comment by LuiseFreese** [comment]
Hey Christophe @PathToSharePoint ,

nothing changed from my perspective about your demo - looking forward to see this in action 🚀

**Comment by PathToSharePoint** [comment]
@LuiseFreese Thanks!

**Pull request merged**
