### PR TITLE
Add new Sample -- React Private Libraries

### PR DESCRIPTION
**Pull request by russgove**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | no                                |
| New sample?     | yes                               |

### CODE REVIEW

**Comment by russgove** [comment]
Added sitescript to create the lists

**Comment by hugoabernier** [comment]
Thank you @russgove. Would you be interested in demoing this sample on this week's SPFx community call? You'd have 10-13 minutes.

**Comment by russgove** [comment]
Hi hugo,just back from vacation and getting caught up. Can we do the next call?

**Comment by russgove** [comment]
If you guys got one of those ‘presentation skills’ workshops before that , I’d be interested in attending,

**Comment by hugoabernier** [comment]
Perfect @russgove I have you confirmed on the August 12th call.

**Pull request merged**
