### PR TITLE
Soccer Highlights Web Part

### PR DESCRIPTION
**Pull request by jerryyasir**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| New sample?     |  yes                               |

## What's in this Pull Request?

This is a react based web part sample to see soccer highlights. 
Thank you very much for making it possible.

### CODE REVIEW

**Comment by hugoabernier** [comment]
Hey @jerryyasir I'm made some tweaks to the filmstrip layout. Can you review the changes and let me know if you're ok with the changes I made. If you're happy with the changes, I'll process the pull request. If not, I'll revert my changes and process it as you originally submitted.

**Comment by jerryyasir** [comment]
> Hey @jerryyasir I'm made some tweaks to the filmstrip layout. Can you review the changes and let me know if you're ok with the changes I made. If you're happy with the changes, I'll process the pull request. If not, I'll revert my changes and process it as you originally submitted.

Please go ahead and process it. I am sure have done some great magic.  I will test after it goes live :)

**Comment by hugoabernier** [comment]
Thanks @jerryyasir ! Would you be interested in demoing this web part on January 28th's SPFx community call?

**Comment by jerryyasir** [comment]
> Thanks @jerryyasir ! Would you be interested in demoing this web part on January 28th's SPFx community call?

Hey Hugo, Yes. of course but only if you demo the FilmStrips function with me :). Thanks for all the guidance and support. Really appreciated.

**Comment by hugoabernier** [comment]
Sounds like a plan! Thank you again for your contribution!

**Pull request merged**
