### PR TITLE
New Sample react-flighttracker

### PR DESCRIPTION
**Pull request by joaojmendes**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
 
| New feature?    | no                            |
| New sample?     |  yes?                               |
 

## What's in this Pull Request?

 New Sample react-flighttracker

### CODE REVIEW

**Comment by PaoloPia** [comment]
Hi Joao,
Thanks for submitting the sample. I don't see any webApiPermissionRequests in the package-solution.json file, but I see you are referring to granting API permissions. Moreover, when I test the web part I see an exception in console and I don't see anything in the workbench:

TypeError: Cannot assign to read only property '_renderPromiseResolver' of object '#<FlightTrackerWebPart>'

What am I missing? Thanks!

**Comment by joaojmendes** [comment]
Hi Paolo,

Thanks,  the documentation is wrong , Sorry. The sample doesn’t require any API permission.

I saw that I have problems when we ran in debug mode  (?debug=true&noredir=true&debugManifestsFile=https://localhost:4321/temp/manifests.js) or in Workbench, that the errors look like internal errors and not related to the sample itself. If you create a  sppkg  and install on  App Catalog and add the WebpPart  you don’t see that errors ….

This error and behavior start showing recently on workbench and on debug mode. I’m sorry for that . ☹ at this moment I don’t know why it happens .


I’m trying to investigate what is the reason … I suspect it's from Recoil library that I use and keep you informed.

I will update the PR.

Thank you and sorry
João


From: Paolo Pialorsi ***@***.***>
Date: Monday, 14 November 2022 at 10:10
To: pnp/sp-dev-fx-webparts ***@***.***>
Cc: João Mendes ***@***.***>, Author ***@***.***>
Subject: Re: [pnp/sp-dev-fx-webparts] New Sample react-flighttracker (PR #3148)

Hi Joao,
Thanks for submitting the sample. I don't see any webApiPermissionRequests in the package-solution.json file, but I see you are referring to granting API permissions. Moreover, when I test the web part I see an exception in console and I don't see anything in the workbench:

TypeError: Cannot assign to read only property '_renderPromiseResolver' of object '#'

What am I missing? Thanks!

**Comment by PaoloPia** [comment]
Hi @joaojmendes,
To speed up testing for community people, we think that this sample should be working in debug mode and workbench, too, and not only when deployed as an SPPKG file in the App Catalog.
If you can, please investigate what the issue is and if it is something dependent on Microsoft, don't hesitate to create an issue here: https://github.com/SharePoint/sp-dev-docs/issues.
Meanwhile, I will wait to merge this sample. Please, keep me updated.

Thanks a lot!

Paolo

**Comment by joaojmendes** [comment]
Hi Paolo,

I discovered the problem; it was really Recoil library.
I fixed it and now everything works fine in Workbench and in debug mode

I will update the PR tomorrow .

Thank you very much.
João

From: Paolo Pialorsi ***@***.***>
Date: Monday, 14 November 2022 at 15:36
To: pnp/sp-dev-fx-webparts ***@***.***>
Cc: João Mendes ***@***.***>, Mention ***@***.***>
Subject: Re: [pnp/sp-dev-fx-webparts] New Sample react-flighttracker (PR #3148)

Hi @joaojmendes<https://github.com/joaojmendes>,
To speed up testing for community people, we think that this sample should be working in debug mode and workbench, too, and not only when deployed as an SPPKG file in the App Catalog.
If you can, please investigate what the issue is and if it is something dependent on Microsoft, don't hesitate to create an issue here: https://github.com/SharePoint/sp-dev-docs/issues.
Meanwhile, I will wait to merge this sample. Please, keep me updated.

Thanks a lot!

Paolo

**Comment by joaojmendes** [comment]
HI @PaoloPia , updated the docs and tested in Workbench and Debug mode.
Screenshot 2022-11-14 at 23 38 51
Screenshot 2022-11-14 at 23 38 21

**Comment by PaoloPia** [comment]
Thanks @joaojmendes! Tonight or tomorrow I will test it again and merge it. Thanks for your work!

**Comment by PaoloPia** [comment]
Hi @joaojmendes,
Thanks again for your contribution.
Any chance you'd be interested in doing a live 10-15 min demo on this in our upcoming community calls? A good demo structure would be to have a few slides explaining the scenario and why it matters, then do a live demo and then move to code to show the key parts.

If you are interested, please submit your demo via this form: https://aka.ms/m365pnp/request/demo

Thanks!

**Pull request merged**
