### PR TITLE
Added a group membership manager sample

### PR DESCRIPTION
**Pull request by techienickb**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                             |
| New feature?    | no                               |
| New sample?     | yes                               |

## What's in this Pull Request?

New Sample for managing group membership of AAD groups which the user owns.  Showcases graph calls and fluent ui 9

### CODE REVIEW

**Comment by hugoabernier** [comment]
Thanks, @techienickb . Would you mind updating the following items before we can merge the sample?

- Building leads to eslint issues -- especially relating to implicit any errors.
- Unable to resolve project "@microsoft/microsoft-graph-clientV3". Ensure it has been linked.
- Unable to resolve project "msalLegacy". Ensure it has been linked.
- README.md should include details about required permissions

**Comment by techienickb** [comment]
@hugoabernier I don't get those errors when I build

import { MSGraphClientV3 } from '@microsoft/sp-http';

```
➜ gulp bundle --ship
Build target: SHIP
[22:11:28] Using gulpfile H:\source\repos\sp-dev-fx-webparts\samples\react-group-membership-manager\gulpfile.js
[22:11:28] Starting 'bundle'...
[22:11:28] Starting gulp
[22:11:28] Starting subtask 'pre-copy'...
[22:11:28] Finished subtask 'pre-copy' after 44 ms
[22:11:28] Starting subtask 'copy-static-assets'...
[22:11:29] Starting subtask 'sass'...
[22:11:29] Finished subtask 'sass' after 559 ms
[22:11:29] Starting subtask 'lint'...
[22:11:29] [lint] eslint version: 8.7.0
[22:11:29] Starting subtask 'tsc'...
[22:11:29] [tsc] typescript version: 4.5.5
[22:11:29] Finished subtask 'copy-static-assets' after 631 ms
[22:11:36] Finished subtask 'tsc' after 6.79 s
[22:11:36] Finished subtask 'lint' after 6.87 s
[22:11:36] Starting subtask 'post-copy'...
[22:11:36] Finished subtask 'post-copy' after 246 μs
[22:11:36] Starting subtask 'configure-webpack'...
[22:11:36] Finished subtask 'configure-webpack' after 241 ms
[22:11:36] Starting subtask 'webpack'...
[22:12:00] Finished subtask 'webpack' after 24 s
[22:12:00] Finished 'bundle' after 32 s
[22:12:01] ==================[ Finished ]==================
[22:12:02] Project group-membership-manager version:0.0.1
[22:12:02] Build tools version:3.17.19
[22:12:02] Node version:v16.17.0
[22:12:02] Total duration:36 s
```

**Comment by hugoabernier** [comment]
Thank you @techienickb. Would you be interested in presenting this on the November 17th community call?

**Comment by techienickb** [comment]
I think I filled the form in to do a smaller presentation on using Fluent UI 9 in SPFx, happy to do that or this which ever you feel is better for the community.  I sadly can't make the 17th, I have a customer engagement (setting up Teams Phone system), but I can do the one 2 weeks after that

**Pull request merged**
