### PR TITLE
React Soccer Highlights Web Part

### PR DESCRIPTION
**Pull request by jerryyasir**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| New sample?     | no - yes?                               |

## What's in this Pull Request?

This is a new React based Soccer Highlights web part that uses a public Soccer API.

### CODE REVIEW

**Comment by hugoabernier** [comment]
Hey @jerryyasir this is a great web part. I don't seem to be able to get the pagination to work, though. Is it supposed to show a different subset of highlights when you click on a page index?

Do you mind confirming that it works for you?

**Comment by jerryyasir** [comment]
> Hey @jerryyasir this is a great web part. I don't seem to be able to get the pagination to work, though. Is it supposed to show a different subset of highlights when you click on a page index?
> 
> Do you mind confirming that it works for you?

The API provides a max of 100 highlights and then I page them.  Did you tried the double click for paging? I will check today and will update.

**Comment by jerryyasir** [comment]
> Hey @jerryyasir this is a great web part. I don't seem to be able to get the pagination to work, though. Is it supposed to show a different subset of highlights when you click on a page index?
> 
> Do you mind confirming that it works for you?

Hi Hugo,
I have replaced the paging with a new component.  It works not but got stuck with a issue.  The component does not show any highlights when it load.  Clicking on Page number does show the data but not sure what is missing.  Not sure exactly what is missing.

**Comment by hugoabernier** [comment]
@jerryyasir  I'll take a look at it. How would you feel if I changed it to use the filmstrip layout to mimic the News web part? (see below)

Filmstrip layout

**Comment by jerryyasir** [comment]
> @jerryyasir I'll take a look at it. How would you feel if I changed it to use the filmstrip layout to mimic the News web part? (see below)
> 
> image
> 
> (You can see the animated GIF version of this image at: )
> https://tahoeninjas.blog/wp-content/uploads/2019/07/FilmstripInAction.gif

That is a great idea which may remove the need for Paging.  Please note that I have not uploaded the new code to the repo? should I simply upload again and submit another PR? 
Thanks for your support.

**Comment by hugoabernier** [comment]
@jerryyasir sure that works for me

**Comment by jerryyasir** [comment]
> @jerryyasir sure that works for me

Looking good. Thanks for great suggestion and off course an awesome blog. 
LookingGood

Still Work in progress.  Next step is playing the video in dialog.  Will update once done.

**Pull request closed without merging**
