### PR TITLE
Invocation of third party (github) API in pnpjs v3 sample- 

### PR DESCRIPTION
**Pull request by divya-akula**
> By submitting this pull request, you agree to the [contribution guidelines](https://github.com/pnp/sp-dev-fx-webparts/blob/main/CONTRIBUTING.md)

> If you aren't familiar with how to contribute to open-source repositories using GitHub, or if you find the instructions on this page confusing, [sign up](https://forms.office.com/Pages/ResponsePage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUREZVRDVYUUJLT1VNRDM4SjhGMlpUNzBORy4u) for one of our [Sharing is Caring](https://pnp.github.io/sharing-is-caring/#pnp-sic-events) events. It's completely free, and we'll guide you through the process.

> To submit a pull request with multiple authors, make sure that at least one commit is a co-authored commit by adding a `Co-authored-by:` trailer to the commit's message. E.g.: `Co-authored-by: name <name@example.com>`

|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                            |
| New feature?    | no                               |
| New sample?     | yes                          |
| Related issues? | #  |

## What's in this Pull Request?

This sample helps to invoke a third part api using a react application which is created with PnPjs v3

### CODE REVIEW

**Comment by hugoabernier** [comment]
Thanks for your sample, but we'll need a completed README so we can feature it in our gallery.

**Comment by divya-akula** [comment]
@hugoabernier I am sorry , I guess I really messed up the readme.md commits will find my actual version or redo the existing one as soon as possible.

**Comment by divya-akula** [comment]
@hugoabernier  sorry there was a confusion, I have deleted the stale sample and my sample exists here https://github.com/divya-akula/sp-dev-fx-webparts/tree/main/samples/react-pnpjs-http-client

**Comment by divya-akula** [comment]
The readme.md is upto date in this sample, which is part of current pull request and sorry for too many comments 
 https://github.com/divya-akula/sp-dev-fx-webparts/tree/main/samples/react-pnpjs-http-client

**Comment by hugoabernier** [comment]
Thank you @divya-akula! Much appreciated!

**Pull request merged**
