### PR TITLE
Fix problems with date handling and redirect after edits

### LINKED ISSUE #1450: React list form does not redirect on submit in Internet Explorer 11
Sample (which sample are you having trouble with)
**React list form**

Authors
**Dany Wyss** @harshagracy

Expected or Desired Behavior
When a form is submitted using the React list form the page should successfully redirect to the page specified in the web part settings. 
image

Observed Behavior
Form does not redirect to specified page. the following error is returned:
**Error on loading lists: TypeError: Object doesn't support property method 'find'**
image

This feature works perfectly well in Google Chrome. 

## Steps to Reproduce

1. Deploy React list form to App catalog
2. Add web part to page
3. Configure settings and include a SharePoint page for the form to redirect to.
4. Fill in form and submit. Error message above returned. 

# Environment Details (*Development & Target environment*)

- **OS**: Windows 10
- **Target Environment**:  SharePoint Online
- **Framework**: [e.g. .NET Framework v3.x | .NET Core v3.x | Node.js v6/v8/v10/v12]
- **Browser(s)**: IE v11 
- **Tooling**: SPFx v1.10.0 
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

### LINKED ISSUE #1451: React list form: Date picker no longer works
Sample (which sample are you having trouble with)
**React list form**

Authors
**Dany Wyss @harshagracy**

Expected or Desired Behavior
When a form contains a date field, user should be able to choose a date using the date picker or manually type a valid date into the input field.

Observed Behavior
Date field displays 'invalid date' placeholder text and does not allow user to add a date using the date picker or type a date manually. If a date is selected the entire form disappears and an error message is displayed. 

image

Error message after picking a date:
**Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.**

image

Steps to Reproduce

1. Deploy React list web part to App catalog
2. Add web part to page
3. Configure settings and add a list with a date field

 Environment Details (*Development & Target environment*)

- **OS**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**:  Node.js v10
- **Browser(s)**: Chrome v79 | Safari v22 | FireFox v31 | IE v11 | Edge | Chromium Edge v79
- **Tooling**: SPFx v1.10.0 
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

### PR DESCRIPTION
**Pull request by sharepointknight**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | yes                               |
| New feature?    | no                                |
| New sample?     | no                               |
| Related issues? | fixes #1451, Fixes #1450    |

## What's in this Pull Request?
Fix problems with date handling in Internet explorer and redirects after edits in IE

### CODE REVIEW

**Comment by PopWarner** [comment]
Thanks @sharepointknight! 

Quick question before we merge this PR, we noticed you listed #1450 as partially. It looks like you fixed the issue based on your PR comments, but wanted to clarify if it was only a partial fix? Thanks!

**Comment by sharepointknight** [comment]
I believe it fixes it but when I first tried submitting the PR it wasn't letting me submit with completing two issues, I thought, so I moved it to partial to see if that was the issue. Then it still wouldn't so I canceled and tried again and it worked. So it should fix both issues.
    On Thursday, October 1, 2020, 07:44:15 PM PDT, David Warner II <notifications@github.com> wrote:  
 
 


Thanks @sharepointknight!

Quick question before we merge this PR, we noticed you listed #1450 as partially. It looks like you fixed the issue based on your PR comments, but wanted to clarify if it was only a partial fix? Thanks!

**Comment by hugoabernier** [comment]
Thank you @sharepointknight! Great work fixing those two issues!

**Comment by JenniferUN** [comment]
Thank you so much @sharepointknight for fixing all of the listed issues with the React List Form! This is very much appreciated :)

**Pull request merged**
