### PR TITLE
Instagram feed webpart

### PR DESCRIPTION
**Pull request by reshmee011**
## What's in this Pull Request?
  Sample web part to showcase an Instagram feed using the swiper library and Instagram Basic Display API. It is an upgraded version to SPFx 1.16.1 of the web part described in the blog post https://medium.com/arfitect/instagram-feed-in-spfx-web-part-61f76fe1ded4 by Buse Kara

### CODE REVIEW

**Comment by hugoabernier** [comment]
Thank you @reshmee011 ! Would you be interested in presenting this solution on the June 1 [Viva Connections & SharePoint Framework Community Call](https://pnp.github.io/#community). You'd have 10-13 minutes to dome the web part and review the relevant parts of your code.

**Comment by reshmee011** [comment]
@hugoabernier : Thanks so much for merging the PR. I am a bit doubtful because the solution is not really mine. I have just upgraded a solution built by someone else. I have reached out to the person on Linkedin but have not got any response. Let me know your thoughts. I am just starting on my journey on SPFx and looking at existing samples and making them work by upgrading them is a great way to learn. Let me know your thoughts.

**Comment by reshmee011** [comment]
@hugoabernier : I have heard back from Buse Kara and she was supportive and appreciative of the idea of a demo with a mention to her name. I have never presented on the call before, any tips to get prepared would be great. 1st June is a long time away, hope there won't be any issues on the day. I will be happy to attempt the demo.

**Comment by hugoabernier** [comment]
Perfect, I have you confirmed for June 1st. Feel free to reach out to @PopWarner or  myself if you need guidance presenting on a call.

**Comment by reshmee011** [comment]
Hi Hugo

Hope you are doing well. Yourself and David are doing amazing with the
additional humour on the PowerPlatformConnections which makes it look so
fun. I wish I had your natural sense of humour.
Thank you very much again for the opportunity to do a demo. I will use it
as a learning experience and challenge myself so that I can do it.
As the 1st June is approaching, I would like some guidance on a call. I
have never presented on such a large scale and hoped to be able to keep my
nerves under control. I think the demo might be short as the webpart does
not  have many features. Is it fine if it ends up being shorter than 10-13
mins? I might mention some alternative achieving the same requirements
using the low code no code solution using the Instagram Basic Display
independent publisher connector with view formatting which might make the
demo be up to 10-13.

Thanks and Regards
Reshmee

**Pull request merged**
