### PR TITLE
added new sample to show how to manage data onedrive applications folder

### PR DESCRIPTION
**Pull request by Adam-it**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | no                               |
| New sample?     | yes                               |

## What's in this Pull Request?
the aim of this PR is to add a new sample which consists of two solutions (Spfx library and webpart). The library is a ready to use functionality that allows the user to store data in personal applications folder in onedrive using MSGraph. Webpart presents in a very simple way how we may use this library component in our solution to get or save data. 
Saving data in onedrive personal folder is a very convenient way to store our solutions configuration data and is a good alternative to storing data in some configuration sharepoint list or user profile service

### CODE REVIEW

**Comment by hugoabernier** [comment]
Thanks @Adam-it this sample is going to be a great addition to this sample gallery.

I would love to add a little more instructions to the readme on how to debug the solution without deploying it, as we know that most users of this repo prefer to debug the solution before they go through the process of building and deploying the solution.

I have started the script to automate this for remote containers, but can you add a little info on how to debug this solution in the readme and i'll use those instructions to update the container script?

**Comment by Adam-it** [comment]
@hugoabernier sure thing. Very good comment 👍 thanks.

**Comment by Adam-it** [comment]
hi @hugoabernier, 
Sorry for the delay, our life lately changed and we now spend most of our time in support in anyway we can to our neighbors. Anyway, please check the latest commit 
https://github.com/pnp/sp-dev-fx-webparts/pull/2365/commits/f6b26e184f4059b5d08464033e9283fe854951a5
If this is the type of instructions you were looking for?

**Comment by Adam-it** [comment]
BTW I just noticed you mentioned my cute find parker webpart in last community call 🤩. I wasn't present on the call (no time for that now) but I am very happy/proud that you used my webpart as an example for the dev containers (cool feature 😎 and great work 👍).

**Comment by hugoabernier** [comment]
Thank you @Adam-it for your sample and your patience! Would you be interested in presenting your web part on the May 5th community call? You would have 10-13 minutes to demo the web part and review the most important parts of your code.

Also, we'd love for you to write a short blog post on the new PnP blog! If you're interested, follow the instructions on the [contribution guide](https://github.com/pnp/blog/blob/main/CONTRIBUTING.md).

**Comment by Adam-it** [comment]
> Thank you @Adam-it for your sample and your patience! Would you be interested in presenting your web part on the May 5th community call? You would have 10-13 minutes to demo the web part and review the most important parts of your code.
> 
> Also, we'd love for you to write a short blog post on the new PnP blog! If you're interested, follow the instructions on the [contribution guide](https://github.com/pnp/blog/blob/main/CONTRIBUTING.md).

that's totally fine. Everyone is contributing after working hours so I know it's sometimes very hard to find this additional time to to a bit of coding for free 😋. Anyway thank you very much for pushing this PR 👍. 
As for the community call, sure I may try my best 😉. TBH presenting is not my cup of tea but I may give it a shot 👍.
As for the blog post regarding this approach it is already "work in progress" but also here I did not find much time to focus on it, but will try to improve that now 👍. Thanks for the link 👍. TBH I did not notice you may contribute a blog post with a PR to the repo, this is cool  🤩. I always done it with the "Create New Article" button on the Microsoft365PnPBlog page 😉

**Comment by hugoabernier** [comment]
Perfect! I have confirmed you on the agenda!

Don't worry about public speaking! We have the [PnP buddy system](https://forms.office.com/Pages/ResponsePage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUMjRRUVg4NElZUUJLTEY1TVVSVDJFRFpLRS4u) where you can request for a "buddy" to help you prepare. We can help you create what me call a "presentation on rails" which eliminates all the stress of presenting. Feel free to DM me directly on Twitter or LinkedIn and send me your email address and we'll get you set up.

Thanks for sharing your code with the community, and for selflessly agreeing to go out of your comfort zone!

**Pull request merged**
