### PR TITLE
Upgraded the solution react-adaptive-cards-image-gallery to SPFx v1.10

### PR DESCRIPTION
**Pull request by nanddeepn**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                                |
| New feature?    | yes                               |
| New sample?     | no                               |

## What's in this Pull Request?
- Upgraded the solution react-adaptive-cards-image-gallery to SPFx v1.10
- Used arrow function instead of function expression

### CODE REVIEW

**Comment by hugoabernier** [comment]
@nanddeepn this looks like a great sample, but I can't get it to work.

Are you expecting a list name, list URL, or something else in the property pane?  I'd suggest using the PnP list picker to make it more obvious. From looking at the code, it is expecting a list title, but I couldn't get that to work.

I keep on getting this error:
```
AdaptiveCardsImageGallery.tsx:45 Uncaught (in promise) TypeError: Cannot read property 'Url' of undefined
    at AdaptiveCardsImageGallery.tsx:45
    at Array.forEach (<anonymous>)
    at AdaptiveCardsImageGallery.tsx:42
```

I'm sure the issue is on my side. Maybe you need to provide more detailed instructions on what needs to be done to get it to work?

**Comment by nanddeepn** [comment]
Hi @hugoabernier 
Thank you for your review. 

This sample has a pre-defined list schema to work with. The sample creates a custom list and loads the data from that list. 
I agree with you, that on initial load the web part should not show the error as you reported. I will set the default values for the web part properties to resolve this.

Thank you.

**Comment by nanddeepn** [comment]
Hi @hugoabernier 
Made commit https://github.com/pnp/sp-dev-fx-webparts/pull/1340/commits/285f64a396886b5620a7fa7ef47bbd5c844ce0e8 for setting default list name as web part property, so that it will not error out on the initial load.
Please review. Thanks!

**Comment by hugoabernier** [comment]
Thanks @nanddeepn. I tried the recent PR and I'm still experiencing the same issue. It did auto-populate the library name this time, but I get the permanent spinning circle and the following error:

```
AdaptiveCardsImageGallery.tsx:45 Uncaught (in promise) TypeError: Cannot read property 'Url' of undefined
    at AdaptiveCardsImageGallery.tsx:45
    at Array.forEach (<anonymous>)
    at AdaptiveCardsImageGallery.tsx:42
```

I can confirm that the Adaptive Card Images library is provisioned with a **Title** column, but it does not provision any of the following columns:
- Image Link
- Navigation URL
- Sort Order

After adding the columns manually, it works.

My suggestion is that if you're unable to fix the list provisioning, you might want to include instructions in your README.md on how to configure the columns -- but the list provisioning component working would be a fantastic addition to the sample.

Thanks for your hard work!

**Comment by nanddeepn** [comment]
Hi @hugoabernier 
Thanks for your comments.

One thing, I wanted to check with you - Did you remove the SharePoint list "Adaptive Card Images", when you removed the old version of app?
I think, you must have. But, still just wanted to check.

The documentation (README.md) mentions the schema needed by the SharePoint list "Adaptive Card Images".
https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-adaptive-cards-image-gallery

**Comment by hugoabernier** [comment]
@nanddeepn yes I did. I used the picture to add the missing columns (that's how I was able to confirm that the provisioned list was missing the three columns, and that the web part works once the list is created).

**Comment by nanddeepn** [comment]
Hi @hugoabernier 
Made commit https://github.com/pnp/sp-dev-fx-webparts/pull/1340/commits/d123500b32cc58f899bc9eabac8732b878306fb7
I have updated the asset provisioning to provision the list with required schema. 

Please re-check. Thank you :)

**Comment by hugoabernier** [comment]
@nanddeepn I still had the same issue where the list didn't get all the columns that it should, but I'll go ahead and merge the PR and hope that nobody else has the same issue as me.

Thanks for your contribution.

**Comment by nanddeepn** [comment]
Thank you @hugoabernier

**Pull request merged**
