### PR TITLE
New Sample Follow Document WebPart

### PR DESCRIPTION
**Pull request by aaclage**
> By submitting this pull request, you agree to the [contribution guidelines](https://github.com/pnp/sp-dev-fx-webparts/blob/main/CONTRIBUTING.md)

> If you aren't familiar with how to contribute to open-source repositories using GitHub, or if you find the instructions on this page confusing, [sign up](https://forms.office.com/Pages/ResponsePage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUREZVRDVYUUJLT1VNRDM4SjhGMlpUNzBORy4u) for one of our [Sharing is Caring](https://pnp.github.io/sharing-is-caring/#pnp-sic-events) events. It's completely free, and we'll guide you through the process.

|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                              |
| New feature?    | no                               |
| New sample?     |yes                               |

## What's in this Pull Request?
@hugoabernier follow up from project "Follow Document" extension.
https://github.com/pnp/sp-dev-fx-extensions/tree/main/samples/react-command-follow-document

This solution has the goal to easily identify/follow user key documents from all Tenant and easily access them in Modern Pages and Microsoft Teams. This solution uses the Out of Box Social feature "Follow Document WebPart" with combination of MSGraph queries and extension for Microsoft Teams.

This is a 2 phase project with associated dependency of solution "Follow-Document" extension where users are allow to select and manage Followed Document in Libraries to be used in this project.

Available features:

- Display Follow Documents as Document Card Grid.
- Click on icon redirects to Document.
- Click on Site name redirects to Site.
- Team icon, Form to send message with html to Teams using adaptive cards.
- Folder Icon redirects to Library where document is located.
- Filled Start allow user to unfollow document.
- Info icon open the Properties of Document with capability to edit.
- Document with search icon allow to preview Document in Side Panel.
- Search by Filename.
- Grouping by Site.
- Microsoft Team integration with personal/Tab App that allow user focus on key Documents.

Usage of following Technologies:
- Usage of Social Feature "Follow" documents and associated REST "/_api/social.following/"
- Usage of Graph queries using Graph explorer
- Usage of adaptive cards
- Microsoft Teams integration with following option [TeamsTab, TeamsPersonalApp]

image

### CODE REVIEW

**Comment by hugoabernier** [comment]
Thanks @aaclage, I'll process this PR later this week.

**Comment by aaclage** [comment]
Hi @hugoabernier ,

One question if the sample is approved and since you ask to present the dependent sample on 1 july
https://github.com/pnp/sp-dev-fx-extensions/pull/399, can join together and present both samples. Is that ok?

**Comment by hugoabernier** [comment]
Sure, if you feel that you can do justice to both web parts in 10 to 13 minutes, you're welcome to do so.

**Comment by aaclage** [comment]
Thank you @hugoabernier just to make the story complete and samples are simple anyway...

**Comment by hugoabernier** [comment]
Cool new web part @aaclage! Thanks for the sample

**Pull request merged**
