### PR TITLE
React list form

### LINKED ISSUE #1452: React list form: Support for People Picker, Attachments and Managed Metadata fields
Sample (which sample are you talking about)
**React list form**

Authors
**Dany Wyss, @Harshagracy** 

Suggestion (the more details, the better)

**Firstly, a big thank you to the authors of this solution for all the hard work you put in to developing this fantastic web part. I'm sure it has helped many organisations where PowerApps is currently not an available option. 

I know that this has been requested quite a few times by different contributors but it would be really helpful if support for 'Person or Group' (people picker), 'Attachments' and 'Managed Metadata' fields were added to this solution.

It would literally be a game changer!!!** 

image

### PR DESCRIPTION
**Pull request by sharepointknight**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | no                               |
| New sample?     | no                               |
| Related issues? | fixes #1452  |

## What's in this Pull Request?

Added support for the User and Taxonomy fields by incorporating PnP React controls to the react-list-form sample. Includes support for multi select and different scenarios for user fields.

### CODE REVIEW

**Comment by hugoabernier** [comment]
Thank you @sharepointknight for this awesome update!

**Comment by hugoabernier** [comment]
Hey @sharepointknight, it would be a good idea to remind people that this web part exists, and to highlight the changes you've made to it. 

Would you be open to demoing it on the October 8th SPFx community call?

**Comment by sharepointknight** [comment]
Sure I'd love to.

**Comment by hugoabernier** [comment]
Perfect @sharepointknight, I have you confirmed for the October 8th call. Looking forward to your demo!

**Pull request merged**
