### PR TITLE
[react-advanced-page-properties] Fix retrieving fields from SitePages

### LINKED ISSUE #2184: react-advanced-page-properties Unable to see more than "Title" property
### Sample

react-advanced-page-properties

### Author(s)

@mhomol

### What happened?

The Advance Page Properties addin is only showing the "Title" property, despite several other Site Columns applied on the page (of various types, e.g. People, Multi-Line, Category, Managed Metadata, etc.).

### Steps to reproduce

1. Generate demo environment from MS, create and add custom Site Columns to Site Pages library. Create a sample page and add a sample value for each of your columns.
2. Clone repo, run `npm install`, `gulp bundle --ship`. and `gulp package-solution --ship`. 
3. Uploade the packaged solution to the App Catalog in the demo environment. Trust it and then added it to the demo site.
4. On your page, add the Advanced Page Properties webpart. It contains only the Title property, no other properties.

### Expected behavior

Would expect to see the custom site columns I added available for use within this webpart.

### Target SharePoint environment

SharePoint Online

### Developer environment

_No response_

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Node.js version

v10.13.0

### Additional environment details

Noticed when running `gulp bundle --ship`:
"Browserslist: caniuse-lite is outdated. Please run: npx browserslist@latest --update-db"
"Warning - tslint - src\webparts\advancedPageProperties\components\AdvancedPageProperties.tsx(108,18): error no-use-before-declare: variable 'RenderPagePropValue' used before declaration"
"The build failed because a task wrote output to stderr. Exiting with exit code: 1"

I tried bundling the solution with the current version of the code and also a historical version when the first version didn't work. Both had the same issue, only Title was available for use.

### PR DESCRIPTION
**Pull request by Abderahman88**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | yes                             |
| New feature?    | no                             |
| New sample?     | no                             |
| Related issues? | fixes #2184 ,  |

## What's in this Pull Request?
Fields where retrieved for an incorrect list (SiteAssets). 
Added a correction for using the correct list (SitePages).

### CODE REVIEW

**Comment by hugoabernier** [comment]
Thank you @Abderahman88 !

**Comment by rgmatthes** [comment]
I'm sorry, but while this is improved, there's still a bug here. :(

The good: The webpart can now correctly retrieve site columns on the Site Pages library, and displays them in a dedicated pane on the right side of the browser window when configuring the webpart.

The bad: Neither the web part preview nor the published page show any of the properties selected via the configuration step. The webpart title is there and configurable, but no other properties appear.

I'm sorry for this headache. I appreciate your continued efforts to make this work!!

**Comment by rgmatthes** [comment]
@Abderahman88 Ahh, ok, this is actually _mostly_ working! Some site column types don't work, which causes the entire webapp to fail by failing to update the webpart's display, either in preview or published status.

To elaborate, if I add site columns of a type known to work, then the app works exactly as expected! However, if I add a site column of a type that doesn't work, the webpart preview display fails to update when configuring the webpart, and the webpart on a published page will contain no properties.

In my brief testing, the site column types that don't work are:
- People
- Managed Metadata
- Lookup

**Comment by Abderahman88** [comment]
@rgmatthes

Yes, some fieldtypes will not work. (boolean, person,...)
This is restricted by the code.

```
 if (!f.FromBaseType && !f.Hidden && f.SchemaXml.indexOf("ShowInListSettings=\"FALSE\"") === -1
          && f.TypeAsString !== "Boolean" && f.TypeAsString !== "Note" && f.TypeAsString !== "User") {
        this.availableProperties.push({ key: f.InternalName, text: f.Title });
        Log.Write(f.TypeAsString);
      }
```

**Comment by HamEv** [comment]
@Abderahman88 why is that restricted by code? I have to show people fields, too in my page properties (default sharepoint webpart can do that).

Could you fix this, please?

**Pull request merged**
