### PR TITLE
Added react-teams-graph-upload-as-pdf sample

### PR DESCRIPTION
**Pull request by mmsharepoint**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | no |
| New sample?     | yes|
| Related issues? | |

## What's in this Pull Request?
As requested this is my sample from the PnP client-side dev call 19-Nov-2020.
I might have not submitted it in time cause at the same point of time I created a further sample as teams tab with backend code for the up- and download functionality.
(https://github.com/pnp/teams-dev-samples/tree/main/samples/tab-sso-graph-upload-as-pdf)

### CODE REVIEW

**Comment by hugoabernier** [comment]
Thank you @mmsharepoint for the great sample!

Would you be interested to demo this sample on the January 27th SPFx community call? You'd have 10-13 minutes to show the functionality and walk through the code highlights.

Let me know and we'll put you on the agenda!

**Comment by mmsharepoint** [comment]
Hi @hugoabernier 
of course I always like to demonstrate samples in the community calls and especially in the SPFx call where I wasn't presenter for a while now...
But as you might remember this specific sample I already presented last year and you only got back to me as it was not yet part of this repo ...:
https://github.com/mmsharepoint/react-teams-graph-upload-as-pdf/issues/2 

I have the yo teams alternative with up-/download operations in the backend as well which was not yet demoed, but ...
https://github.com/mmsharepoint/tab-sso-graph-upload-as-pdf

**Comment by hugoabernier** [comment]
@mmsharepoint how about we add the SSO Graph Upload as PDF sample, and we can schedule you on that same date -- if you're up to it. I can go grab the code sample myself, or I can wait for you to do a pull request. Let me know how you want to proceed!

**Comment by mmsharepoint** [comment]
> @mmsharepoint how about we add the SSO Graph Upload as PDF sample, and we can schedule you on that same date -- if you're up to it. I can go grab the code sample myself, or I can wait for you to do a pull request. Let me know how you want to proceed!

The sample is already shared in the teams repo @hugoabernier 
https://github.com/pnp/teams-dev-samples/tree/main/samples/tab-sso-graph-upload-as-pdf 
So bad for you KPIs but good for Bob's ;-)
If you think it's worth to demo it (although we already had the other sample client-side and SPFx-like) I would of course like to do it. I only think as a Teams sample it better fits to the general dev call? 
Markus

**Pull request merged**
