### PR TITLE
Fix `react-page-navigator` with unique attributes. Closes #2697, #2698, and #2715

### LINKED ISSUE #2697: react-page-navigator - only works with align left
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-page-navigator

### Author(s)

@aakashbhardwaj619

### What happened?

When you format a heading to another alignment except 'Align left', the PageNavigator breaks and is no longer listing the headings correct.

Alignments

### Steps to reproduce

1. Add the PageNavigator web part to the page.
2. Format a heading to 'center', 'align left' or 'justify'.
Alignments
3. Republish the Page and refresh.
4. Look at the PageNavigator.

### Expected behavior

The PageNavigator shows the heading correct even if they are in other text alignments.

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Paste the results of SPFx doctor

Not helping.

### Additional environment details

_No response_

### PR DESCRIPTION
**Pull request by Jwaegebaert**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | yes                               |
| New feature?    | no                            |
| New sample?     | no                              |
| Related issues? | fixes #2697, #2698, and #2715  |

## What's in this Pull Request?

Several issues occurred where the use of characters gave problems within this webpart. In this PR, handling has been added to those special characters within the creation of an anchor url. The logic that was going to catch duplicate headers has also been modified because it wasn't functioning properly.

> react-Page Navigator will have incorrect tags, like this:
..../MyPage.aspx#this-is-summary-page-area-1-2-3-4
When it should be:
..../MyPage.aspx#this-is-summary-page-area

There was also a while loop that went through all available headers. This gave the problem of the webpart crashing because of this loop. This is also adjusted in this PR.

### CODE REVIEW

**Comment by Jwaegebaert** [comment]
Little update. Two issues have just been opened for the webpart `react-page-navigator`. With this PR already being open, I inserted the solution for issue #2698 here as well.

**Comment by mikezimm** [comment]
@Jwaegebaert ,
I am using this as a component in my web part and found a couple other common occurrences with the header text.

comma ==> ,
open parentheses ==>  (
close parentheses ==>  )
hyphen ==> -   for common words like 'high-tech'

I modified your GetAnchorUrl function to the following:
yours:   .replace(/[^a-zA-Z0-9. ]/g, "")
mine:    .replace(/[^a-zA-Z0-9.,()\- ]/g, "")

Updated the comment as well below.

Thanks for the update so far!

```typescript
  private static GetAnchorUrl(headingValue: string): string {
    let urlExists = true;
    // .replace(/[^a-zA-Z0-9.,()\- ]/g, "") replaces chars except a - z, 0 - 9 , ( ) and a . with ""
    // .replace(/'|?|\|/| |&/g, "-") replaces any blanks and special characters (list is for sure not complete) with "-"
    // .replace(/--+/g, "-") replaces any additional - with only one -; e.g. --- get replaced with -, -- get replaced with - etc.
    let anchorUrl = `#${headingValue
      .replace(/[^a-zA-Z0-9.,()\- ]/g, "")
      .replace(/\'|\?|\\|\/| |\&/g, "-")
      .replace(/--+/g, "-")}`.toLowerCase();
    let urlSuffix = 1;
    while (urlExists === true) {
      urlExists = (this.allUrls.indexOf(anchorUrl) === -1) ? false : true;
      if (urlExists) {
        anchorUrl = anchorUrl + `-${urlSuffix}`;
        urlSuffix++;
      }
    }
    return anchorUrl;
  }
```

**Comment by mikezimm** [comment]
@Jwaegebaert ,
One other follow up...
I found through testing that we use the & symbol in a lot of headings (see screenshot for good example).

I noticed in your line 21 that it should replace the & symbol with an - but it does not seem to do that in my case.
      .replace(/\'|\?|\\|\/| |\&/g, "-")

Is it a prior function or regex are replacing the & with empty string before that point so your line 21 is not finding it?

A temporary work around (although it looks a clunky) is to put a space before or after the & symbol.

So to get the link:
Current Text:   PPE PP&E
Required Txt:  PPE PP &E
or:  PPE PP& E
or:  PPE PP & E

image

**Comment by Jwaegebaert** [comment]
Great catch @mikezimm, I included all the extra chars you suggested.

> Is it a prior function or regex are replacing the & with empty string before that point so your line 21 is not finding it?

So, for this part. The problem with line 21 not finding the & char is due to line 20 removing the char. With adding the & char to line 20 we exclude it from our regex expression. `.replace(/[^a-zA-Z0-9.,()\-& ]/g, "")`

**Comment by mikezimm** [comment]
Thanks @Jwaegebaert , tested out the & fix and works like a charm :)

If you want, feel free to try out your example but on a little steroids.  Added some bells and whistles but could not have done it without your groundwor... Thanks! 

https://github.com/mikezimm/PageInfo

**Comment by Jwaegebaert** [comment]
Great to hear that @mikezimm.

I will definitely go and checkout your webpart. 😄

**Comment by dk4dk4** [comment]
Hi, we found this bug today (incorrect anchor tags) as well and have merged the changes in early (I assume the pull request will get approved soon).

I did notice when coming back to a page after 'Republishing' the webpart links will not work due to extra numbers on the end:

react-Page Navigator will have incorrect tags, like this: 
..../MyPage.aspx#this-is-summary-page-area-1-2-3-4
When it should be:
..../MyPage.aspx#this-is-summary-page-area

I can resolve it by doing a browser refresh on the page after landing on the page from a Republish.  This removes the erroneous -1-2-3-4 from the links.  Not sure whats adding the extra -1-2-3-4.  I could also get it to fail by adding a bunch of special characters to end of a header.  

Example header to make it fail:
DK Test()@#$@#_

**Comment by mikezimm** [comment]
@dk4dk4 , @Jwaegebaert ,
I can also confirm the behavior with the -1-2-3-4.  I could never figure out what happens and it is annoying.  In my case, I could only get it to clear that problem if I copied the URL without the numbers and then refreshed.

Would be nice to resolve it though.

**Comment by Jwaegebaert** [comment]
@dk4dk4, @mikezimm. The cause of that problem is the following piece of code. 

https://github.com/pnp/sp-dev-fx-webparts/blob/4a72df3bf8d847a7d1eefbe619915b84fcb5beeb/samples/react-page-navigator/src/Service/SPService.ts#L24-L30

This one is going to see if the header link already exists and is going to append an `-1` to the link. Here I think sometimes the while loop goes wrong and then appends `-1-2-3-4` to the link. To solve this, we'd better start looking at #2715. Here, the idea will be to start refactoring whole the link creation of the webpart to solve multiple problems that are currently occuring.

**Comment by Jwaegebaert** [comment]
Hey @mikezimm and @dk4dk4. Thanks for all your bug reports and suggestions. 

In the last commit, I refactored the logic to get an anchor url and the loop for all the possible headers. Here you will see that all problematic characters are getting handled and the duplicate headers will get accommodated. Hopefully this helps you a little further.

**Comment by Jwaegebaert** [comment]
Perfect @dk4dk4, great to hear that things are going well!

**Comment by hugoabernier** [comment]
Thank you, merged manually to resolve conflicts.

**Comment by mikezimm** [comment]
@Jwaegebaert ,

I was doing some more testing :)
I found a case where people were using multiple spaces in a heading and it was causing a bug that was very interesting.

## Example heading:  replace {7 spaces} with 7 actual spaces
"4){7 spaces}Test{7 spaces}heading{7 spaces}te{7 spaces}x{7 spaces}t"
- I added lots of spaces to exaggerate and test the issue.

When I use your function in codepen.io screen, it gives the correct tag.  Multiple spaces were trimmed down to just a single -hyphen.

However, when I use the exact same function in my project, it gives strange behaviors.  It's like it is searching for 2 spaces or hyphens at a time and replacing with one.  I'll attach screenshots in a second comment just to keep it clean.

Anyway, I found that if I added this replace
.replace(/\s/g, "")

before your last one
.replace(/--+/g, "-")

It fixed the issue in all cases I was able to test.

## Your function... at least I hope it's the latest one :)
```typescript
    let anchorUrl = `#${headingValue
      .toLowerCase()
      .trim()
      .replace(/[{}|\[\]\<\>#@"'^%`?;:\/=~\\]/g, " ")
      .replace( /^\-*|\-*$/g , "")
      .trim()
      .replace(/\'|\?|\\|\/| |\&/g, "-")
      .replace(/--+/g, "-")
    }`;
```

**Comment by mikezimm** [comment]
@Jwaegebaert 
Here are some screenshots showing the function in both Codepen.io as well as when I step through it in my project

## Codepen result -
NOTE this screenshot had a slightly older test string from my previous comment but the results were consistant.
image

## Similar step through in my project
Here  the code is stopped at line 27 and if you look at the red arrow, it shows the current value.
Correct value:  "#4)-test-heading-te-x-t"
Actual value: "#4)---test---heading-te-x-t"
NOTE in my code, I added line 24 to try and fix but it had no impact on the result in that location.

image

## I broke your function into different lines so I could step through them

### This is before executing line 25 =>  `.replace(/--+/g, "-")`
You see that multiple spaces were converted to ' - - - - ' prior

image

### This is after executing line 25
Here you see the '- ' were replaced with just a single '-'
This is the line that I had to add for it to clean up the multiple spaces in a row.

image

### Finally, this is after executing line 26 which is your last regex replace
It how gives the correct url :)

image

**Comment by mikezimm** [comment]
@Jwaegebaert 

One other side note, while testing your reg expressions on https://regex101.com/,
It gave this error.  I did not throw an error in my project so maybe it's just a nicecity but thought I'd pass it on.
I made the update ( escaping the slash ) and it seemed to work the same.

image

**Comment by mikezimm** [comment]
@Jwaegebaert 
One final final thing I discovered... promise last one of the day

On one page, I noticed a heading that was very long and did not work.

I found that SharePoint 'seems' to cap the #part of the url to 128 characters.

Actual heading text: 129 characters
Revaluation of assets and liabilities for entities with local currency that are different from their OneStream reporting currency

SharePoint hash: 128 characters
revaluation-of-assets-and-liabilities-for-entities-with-local-currency-that-are-different-from-their-onestream-reporting-currenc

## I did a couple really long headings just to be sure and this adjustment seems to cover them:

image

**Comment by Jwaegebaert** [comment]
Great catches yet again @mikezimm! Before we discuss your research, I think it's best we move it into a seperate issue. This way we don't have a discussing running on a closed PR. I will create one shortly containing your research. 😄

**Pull request closed without merging**
