### PR TITLE
version 2 of webpart with new features and bug fixes

### PR DESCRIPTION
**Pull request by bogeorge**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | yes                             |
| New sample?     | no                              |
| Related issues? | n/a |

## What's in this Pull Request?

This is a new and improved version of the React Questions and Answers solution that includes a new editor to support inline images and at mentions.  Updated support for categorization of questions.  Support for Conversations (questions that don't need an answer).  It also now provisions the underlying list so it can be crawled and have questions show in search results.

### CODE REVIEW

**Comment by hugoabernier** [comment]
Thank you @bogeorge! I like the new spiffy update!

**Comment by bogeorge** [comment]
Thanks @hugoabernier.  It was really a shared effort between @mhomol and I for a customer that wanted to enhance version 1.

**Comment by mhomol** [comment]
thanks @hugoabernier.  I was so thrilled to be apart of this with @bogeorge .  It really is a big improvement feature-wise. and was awesome to work on features that are thinking about the end-users so much more.

**Comment by mhomol** [comment]
One other thing worth mentioning is that the support for Categories allows for multiple instances of Questions and Conversations per site collection, whereas before it was one per

**Pull request merged**
