### PR TITLE
React-Kanban-Board rewritten with Office-UI 

### LINKED ISSUE #1288: react-kanban-board dont work properly on IE. Locked on "Loading tasks"
## Authors

@westerdaled 
@RamPrasadMeenavalli 

A working kanban on most navigators.

## Observed Behavior

Internet explorer 11 (tested on 11.836.18362.0 / 11.0.190) can't load  kanban webpart deployed on a sharepoint tenant. IE is blocked on "Loading Tasks". 

Works fine on FF, Chrome and Edge.

## Steps to Reproduce
- npm install
- gulp bundle --ship
- gulp package-solution --ship
- Deploy solution on tenant.
- Load IE and insert a kanban on the page, connect it to a task list and save.
- Kankan tasks will not be displayed.

# Environment Details (*Development & Target environment*)
- Sharepoint Online
-  Windows 10 Pro 64 latest with All navigator updated to latests versions.

### PR DESCRIPTION
**Pull request by petkir**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix        | yes                               |
| New feature    |  yes                               |
| Related issues? | fixes #1288 |

## What's in this Pull Request?

jqwidgets control replaced with a custom React Kanban Board based on Office UI Components and IE11 Support.

Reuse of PNP property pane controls to get a great experience
New Features:
* Order kanban buckets in the property pane (PNP Order PropertyPane)
* Configure bucket in property pane with custom field implementation
* PNP Placeholder control if the web part is not configured
* PNP WebpartTitle control (Including a toggle in PropertyPane to control visibility  )
* PNP List Selection PropertyPane Control (including Filter on BaseTemplateId)

### CODE REVIEW

**Comment by hugoabernier** [comment]
@petkir great work with this one. I hope you don't mind but I upgraded the sample to SPFx 1.10 while I was processing the PR.

**Comment by petkir** [comment]
Thanks @hugoabernier  for doing this upgrade. Next time I will do an spfx upgrade, with codetour. Now I know it.

**Comment by RamPrasadMeenavalli** [comment]
This is amazing @petkir 
Thank you for updating this. It looks a lot better now 👍

**Comment by petkir** [comment]
@RamPrasadMeenavalli thanks for inspiration, without you and the ie11 issue. It would not look like this now.

**Pull request merged**
