### PR TITLE
Ace strategy pattern for multi-action QuickView

### PR DESCRIPTION
**Pull request by mgwojciech**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                             |
| New feature?    | no                            |
| New sample?     | yes                              |
| Related issues? |N\A |

## What's in this Pull Request?

This sample shows how to avoid conditions hell in quick view actions.

With more complex cards it can get extremely difficult to handle all the actions as adding more and more conditions to target action id impacts code readability.

In this sample we are exposing organization news in adaptive card.
To start we introduce Next and Previous action to navigate between loaded news.
We also want to add possibility to like and comment displayed news.
Commenting is actually a two-action operation as first- we have to show the input and then submit value provided in the input.
Finally we add support for posting this news in a Teams channel - this requires calls to get Teams, then Channels for selected Team and finally post the news in selected channel.

Main objective is to present how we can implement QuickView action handling to support testability and making future refactoring easier.

### CODE REVIEW

**Comment by hugoabernier** [comment]
@mgwojciech thanks for the great sample! I am wondering if this sample would get more visibility in the https://github.com/pnp/sp-dev-fx-aces repository?

Happy to have it in this repo, but I'm sure that @PopWarner and @dcashpeterson would love to feature your sample in their repo.

**Comment by mgwojciech** [comment]
hi @hugoabernier if that's ok with everyone I think we can have this one in this repo and I promise I'll do something more on ACE for @PopWarner in sp-dev-fx-aces. 
Sounds good?

**Comment by hugoabernier** [comment]
Perfect, @mgwojciech .  Would you be interested in demoing your sample in the June 30th community call? You'd have 10-13 minutes to demn the concept and walk through the most important code sections

**Comment by mgwojciech** [comment]
@hugoabernier sure thing. More than happy to do it :)

**Pull request merged**
