### PR TITLE
Added PnP JS Tester Webpart

### PR DESCRIPTION
**Pull request by siddharth-vaghasia**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| New sample?     | yes                               |

## What's in this Pull Request?

Added new sample PnP JS Tester Web part which allows us to test the PnP JS SharePoint method.
Co-Authored-By: @kunj-sangani(Kunj Balkrishna Sangani)

### CODE REVIEW

**Comment by hugoabernier** [comment]
Thank you @siddharth-vaghasia this is going to be a very handy web part. Would you be interested in demoing on September 24th's SPFx call?

**Comment by siddharth-vaghasia** [comment]
@hugoabernier thanks, yes...I would be interested...

**Comment by hugoabernier** [comment]
Perfect @siddharth-vaghasia  I have you confirmed on the agenda for September 24th. I look forward to your demo!

**Comment by kathyboilek** [comment]
Fantastic!

**Pull request merged**
