### PR TITLE
Update react-pnpjsexplorer to SPFx1.11.0

### PR DESCRIPTION
**Pull request by joelfmrodrigues**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | no                               |
| New sample?     | no                               |
| Related issues? | no |

## What's in this Pull Request?

Update react-pnpjsexplorer web part to SPFx1.11.0
Note: One of the commits is to revert changes as I created the branch from the wrong base by mistake, but believe all is fine after reverting it.

### CODE REVIEW

**Comment by hugoabernier** [comment]
Thank you @joaojmendes !

**Comment by joelfmrodrigues** [comment]
@hugoabernier close 😁. With the massive number of contributions from @joaojmendes I understand that you are used to @ mention him very often and it's just automatic hehe

**Comment by joelfmrodrigues** [comment]
@hugoabernier on a side note, are the PnP repositories participating in Hacktoberfest? Just came to my thoughts that it could perhaps be a good way to get some extra PRs :)

**Comment by hugoabernier** [comment]
We are discussing the possibility. Will find out shortly

**Pull request merged**
