### PR TITLE
React personal tools list – enhanced web part properties for list handling

### PR DESCRIPTION
**Pull request by tmaestrini**
- [ ] New sample
- [x] update
- [x] Related issues: mentioned in #4745

## What's in this Pull Request?
This PR enhances the existing version of the sample  by providing three additional web part properties: a target site and the two necessary lists can be selected via site picker and list picker components. The components and hooks were adjusted accordingly. The README file contains an according description.

## Node Version
Node version used: 1.18.0

## Checklist 
- [x] My pull request affects only ONE sample.
- [x] My sample builds without any warnings
- [x] I have updated the `README.md` file's **Version history**. For new samples, created a new `README.md` file matching [this template](templates/README-template.md)
- [x] My `README.md` has at least one static high-resolution screenshot (i.e. not a GIF) located in the `assets` folder.
- [x] My `README.md` contains complete setup instructions, including pre-requisites and permissions required
- [x] My solution includes a `.nvmrc` file indicating the version of Node.js

### CODE REVIEW

**Comment by tmaestrini** [comment]
Is there any news on this PR?

**Comment by hugoberniertak** [comment]
@tmaestrini thanks for inquiring. We typically process pull requests once every 2 weeks, except when we're on vacation. I'll be processing the pull request this week/weekend.

**Comment by hugoabernier** [comment]
@tmaestrini thanks for inquiring. We typically process pull requests once every 2 weeks, except when we're on vacation. I'll be processing the pull request this week/weekend.

**Comment by tmaestrini** [comment]
@hugoabernier thank you very much for your reply! GlaD to hear.

**Comment by hugoabernier** [comment]
Thank you @tmaestrini ! Much appreciated!

**Pull request merged**
