### PR TITLE
React faqs

### PR DESCRIPTION
**Pull request by arunkumarperumal**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                              |
| New feature?    | no                              |
| New sample?     | yes                            |
| Related issues? | no |

## What's in this Pull Request?

> New SPFx web part sample : Frequently Asked Questions with Property Field Collection Data
> This Web Part allows users to create Frequently Asked Questions using Property Field Collection Data for SharePoint Online.
> This web part allows to search within questions and answers which are stored in a Property Field Collection Data and can be easily edited inline within the webpart using Property Pane. Search text is highligted in the search results.
> Provides options to view as an Accordion or Tab.
> In mobile browser defaults to Accordion view.

### CODE REVIEW

**Comment by hugoabernier** [comment]
Thank you @arunkumarperumal! Would you be interested in demoing this web part on the June 2nd SPFx community call?

You would have 10-13 minutes to demo your web part and highlight the relevant sections of your code.


Also, we'd love for you to write a short blog post on the new PnP blog! If you're interested, follow the instructions on the [contribution guide](https://github.com/pnp/blog/blob/main/CONTRIBUTING.md).

**Comment by adminM365x180123** [comment]
hello @hugoabernier,  yes certainly can demo the web part on June 2nd SPFx community call. 

I will try to write a blog post on this web part. 

Thanks!!

**Comment by hugoabernier** [comment]
Thank you, @adminM365x180123, I have confirmed you on the agenda.

**Comment by arunkumarperumal** [comment]
@hugoabernier , I have created a blog post related to the sample. Please check and let me know if any changes needed. 

Link to the pull request : https://github.com/pnp/blog/pull/56

**Comment by arunkumarperumal** [comment]
@hugoabernier, can you please update if the demo on June 2nd in the community call still on?

**Comment by hugoabernier** [comment]
> @hugoabernier, can you please update if the demo on June 2nd in the community call still on?

Yes, you are confirmed on the June 2nd community call. @PopWarner will usually reach out the week of to get copies of your slides (if any, but we recommend at least having an intro slide with your name, contact info and/or social media info).

**Pull request merged**
