### PR TITLE
Initial Commit react-azurefunction-northwind2

### PR DESCRIPTION
**Pull request by jtlivio**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| New sample?     | yes                               |

## What's in this Pull Request?

Initial Commit react-azurefunction-northwind2

This Webpart consume an anonymous Function App from an HTTP Triger using the templates from the Northwind Microsoft DBs You must create a database in azure and run the scripts, sample

Working on AAD Client Factory

### CODE REVIEW

**Comment by jtlivio** [comment]
New Sample = Yes

**Comment by hugoabernier** [comment]
Merged via #3122, Thank you @jtlivio

**Comment by VesaJuvonen** [comment]
Hi @jtlivio,
any change you'd be interested on doing a live 10-15 min demo on this in our upcoming community calls? - We would have openings even as soon as 17th of November. Good demo structure would be to have few slides explaining the scenario and why it matters, then do a live demo and then move to code to show the key parts.

Would you be interested on this? If you don't feel comfortable doing the demo personally - we can do the demo for you - and call out that the code was provided by you. 

Let us know. Thx

**Comment by jtlivio** [comment]
Hello @hugoabernier welcome 🤗 @VesaJuvonen I really didn't catch up this comment, sorry for that and thank you for the challenge 😃 If makes sense I'll be glad to present this and how is so easy to implement. I did see @waldekmastykarz recording about consuming anonymous APIs with a function. Let me know. ✌️

**Pull request closed without merging**
