### PR TITLE
#1354 issue fix and package update to spfx version 1.10.0

### LINKED ISSUE #1354: In react-list-form webpart, validation not firing for required list fields before saving the item
https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-list-form
Sample: #react-list-form
Author: @DanyWyss 

## Expected or Desired Behavior
List form should perform validation of all required fields before saving

## Observed Behavior
List form saving the form without any validation of required fields

## Steps to Reproduce
If I leave "Title" field empty, it just shows me message as "Item Added Successfully" after click on save button

image

1. Add the webpart to Modern SharePoint Site
2. Select sample SharePoint List from Properties
3. Try to Save without filling required fields
4. It will show "Item Saved Successfully" message

image

# Environment Details (*Development & Target environment*)
- **OS**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v8
- **Browser(s)**: Chrome v83
- **Tooling**: VS Code | SPFx v1.9.1
- **Additional details**: *It shows required error message for DateTime Field and not for Title*

### PR DESCRIPTION
**Pull request by Harshagracy**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | yes                          |
| New feature?    | no                            |
| New sample?     | no                             |
| Related issues? | fixes #1354  |

## What's in this Pull Request?

- Bugfix for #1354 (Validates required fields)
- Upgraded the sample to SPFx version 1.10.0

### CODE REVIEW

**Comment by hugoabernier** [comment]
Thank you @Harshagracy. Would you mind updating the README.md to reflect that the solution is now using SPFx 1.10 (and to add you as one of the authors too). If you aren't comfortable with taking the credit, you can add a comment in the version history to say that you upgraded it to SPFx 1.10 and fixed the issue.

Also, it would be a good idea to update the package and solution version number. Since the change does not break backward compatibility and you didn't update functionality, you can simply make it version 1.0.3.

I'll keep an eye for further commits and I'll process this PR asap.

**Comment by Harshagracy** [comment]
Sure. Thanks Hugo.

**Comment by hugoabernier** [comment]
Thanks @Harshagracy. I've updated the README to include the version history.

**Comment by Harshagracy** [comment]
Thanks a lot @hugoabernier .

**Comment by shrirampophali** [comment]
Thank you @Harshagracy for fixing the issue 👍 and Thank you @hugoabernier for merging it to package 👍 

Would be really nice to have these unsupported field types also supported in future as well :)

- Person Group
- Managed Metadata
- HyperLink or Picture

**Pull request merged**
