### PR TITLE
react bot framework sso

### PR DESCRIPTION
**Pull request by DingmaomaoBJTU**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                           |
| New feature?    | no                             |
| New sample?     | yes                               |
| Related issues? | fixes #X, partially #Y, mentioned in #Z |

## What's in this Pull Request?
 This sample will show you how to embed a Bot Framework bot into a SharePoint web site with SSO.

There are two parts included in this sample:

1. A login bot sample
1. A web parts sample

The web parts embeds the login bot by using a webchat. As the user has already login in the SharePoint website, we could use [SSO](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication-sso?view=azure-bot-service-4.0&tabs=csharp%2Ceml) to authorize the bot. This sample shows how to do this including:

- Detect and intercept OAuth process.
- Use SharePoint library to get the exchange token and send it back to the bot.

### CODE REVIEW

**Comment by hugoabernier** [comment]
Thank you @DingmaomaoBJTU! As per the previous sample, we'd love to have you present this sample.

Maybe we could combine both demos and highlight the differences between the two demos?

Let me know how you'd like to proceed.

**Comment by DingmaomaoBJTU** [comment]
@hugoabernier  Thanks for your quick response! This sample is an advanced demo which contains lots of steps on how to set up environment, it will be hard for beginners to learn and set up if we merge these two together. So we separate them as two samples, one for beginners to set up a simple security bot, one for advanced users to set up single sign on in sharepoint with bot.

**Comment by hugoabernier** [comment]
@DingmaomaoBJTU I agree, I would much prefer to have you present each sample as two separate demos on two calls instead of combining both; I was simply trying to be mindful of your time.

If you're interested, we can schedule you on the December 17th call.

So, to recap:
- December 3: Secure Bot Framework demo
- December 17: SSO Bot Framework demo

Again, I really appreciate your willingness to demo these awesome samples. I think that many will benefit from your presentation(s).

**Comment by DingmaomaoBJTU** [comment]
Hi Hugo,

Thanks for your detailed information, very helpful~ And thanks for your thoughtful suggestion for the demo time too😄 After discussion in our team, we think might be convenient for us to have a single demo for both samples~ So how about we set up a half an hour call in Dec 3? Is this workable for you?

Thanks,
Qiong

**Comment by hugoabernier** [comment]
@DingmaomaoBJTU, that is great! I'll put you on the agenda for December 3rd on the SharePoint Framework Community Call at 7:00 AM PT / 3:00 PM GMT. You can find more details -- including the link to join the call -- at https://pnp.github.io/.

Don't hesitate to reach out if you have any questions.

**Comment by DingmaomaoBJTU** [comment]
Thanks Hugo~ That looks good to me!

Thanks,
Qiong

**Comment by DingmaomaoBJTU** [comment]
Hi Hugo,

Do I need to simply click this on Dec 3rd to join the meeting right?
[cid:image002.jpg@01D6C74F.E3A19690]
Thanks,
Qiong

**Comment by hugoabernier** [comment]
@DingmaomaoBJTU that is correct.

If you want to add it to your calendar, you can follow this link 
https://aka.ms/spdev-spfx-call

And to join the meeting, you can use the link I sent you or use this aka.ms link:
https://aka.ms/spdev-spfx-call-join

We have 30 minutes reserved for you on Dec. 3 (this week's call). 

I really look forward to your demo. If you need anything from me, you can DM me on Twitter or look for me on the Teams Microsoft tenant.

**Pull request merged**
