### PR TITLE
Upgrade Page Navigator web part from SPFx v1.14.0 to v1.20.0 (latest)

### LINKED ISSUE #5253: Upgrade Page Navigator web part to latest version of SPFx - Refresh Rangers Hacktoberfest Event
##  🎯Aim

The aim of this issue is to upgrade the [Page Navigator](https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-page-navigator) web part sample to the latest version of [SPFx (1.20)](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/release-1.20)

## 🤔 Tips how to get started

To support you in this issue you may use the below tooling:
- [CLI for Microsoft 365](https://pnp.github.io/cli-microsoft365) has a command that will [generate upgrade guidance](https://pnp.github.io/cli-microsoft365/cmd/spfx/project/project-upgrade) for this SPFx project `m365 spfx project upgrade`
- [SPFx Toolkit VS Code extension](https://github.com/pnp/vscode-viva) has an [Upgrade Project](https://github.com/pnp/vscode-viva/wiki/5.5-Actions#upgrade-project) action which generates an `.md` report with upgrade guidance to the latest supported SPFx version

## 📣 What's this event all about

Refresh Rangers is a unique [Hacktoberfest](https://hacktoberfest.com/) event aiming to update our most popular samples 🚀. 
During this, you may obtain a unique Microsoft 365 & Power Platform Community badge - Refresh Rangers 🎖️
To obtain this badge besides opening a PR you also need to [opt-in  the Microsoft 365 & Power Platform Community Recognition Program](https://pnp.github.io/recognitionprogram/#overview) and fill out [this form ](https://aka.us11.list-manage.com/subscribe?u=b3df03dd2b64a3bc8a2a200e8&id=4a558f9e2b)

### PR DESCRIPTION
**Pull request by tmaestrini**
- [ ] New sample
- [x] update
- [x] Related issues: closes #5253 

## What's in this Pull Request?

Upgrades the sample web part from SPFx v1.14.0 to v1.20.0 (latest) and fixes some issues related to this version change.
Also contains updated dependencies for jest in order to make all existing tests executable again.

## Node Version

Node version used: v18.19.1

## Checklist

> This checklist is used to automatically pre-process your pull request; It is meant to help process pull requests in a timely manner, rather than hoops to jump through.
> 
- [x] The pull request affects only ONE sample.
- [x] The sample builds without any warnings.
- [x] I have updated the `README.md` file's **Version history**.
- [x] The `README.md` has at least one static high-resolution screenshot (i.e. not a GIF) located in the `assets` folder.
- [x] The `README.md` contains complete setup instructions, including pre-requisites and permissions required
- [x] The solution includes a `.nvmrc` file indicating the version of Node.js

### CODE REVIEW

**Comment by hugoabernier** [comment]
Thank you @tmaestrini for your update! Much appreciated!.

Thank you for sharing your sample with others - you rock! 👏🥇👩‍💻

**Comment by tmaestrini** [comment]
Hey @hugoabernier! How are you?
Does this eork counts for the "hacktoberfest" contribution?

**Comment by Adam-it** [comment]
> Hey @hugoabernier! How are you? Does this eork counts for the "hacktoberfest" contribution?

yes it should as it was attached to and issue which is labeled with `hacktoberfest` label

**Comment by tmaestrini** [comment]
Thanks for your reply, Adam! 🙌I‘m just asking because hacktoberfest profile page states this:And I thought that I’ve submitted already 3 PR’s.Am 20.10.2024 um 00:58 schrieb Adam Wójcik ***@***.***>:﻿

Hey @hugoabernier! How are you? Does this eork counts for the "hacktoberfest" contribution?

yes it should as it was attached to and issue which is labeled with hacktoberfest label

**Comment by Adam-it** [comment]
> Thanks for your reply, @Adam-it 🙌
> I‘m just asking because hacktoberfest profile page states this:
> 
> image
> 
> And I thought that I’ve submitted already 3 PR’s.

Could you send me over those PRs? So that I may double check if they were linked to an issue with Hacktoberfest label

**Comment by tmaestrini** [comment]
@Adam-it Of course, here they are:
1. https://github.com/pnp/sp-dev-fx-webparts/pull/5287 (This one)
2. https://github.com/pnp/sp-dev-fx-webparts/pull/5300
3. https://github.com/pnp/cli-microsoft365/pull/6413

**Comment by Adam-it** [comment]
> @Adam-it Of course, here they are:
> 1. https://github.com/pnp/sp-dev-fx-webparts/pull/5287 (This one)
> 2. https://github.com/pnp/sp-dev-fx-webparts/pull/5300
> 3. https://github.com/pnp/cli-microsoft365/pull/6413

The second one was not attached to any issue that is most probably why it did not count. I will check if I may amend it

**Comment by Adam-it** [comment]
@tmaestrini I linked the issue to the PR
 Let's see if it will show up in your Hacktoberfest profile in few days 👍

**Comment by tmaestrini** [comment]
Thanks, Adam! :)

**Comment by tmaestrini** [comment]
> The second one was not attached to any issue that is most probably why it did not count. I will check if I may amend it

That's strange. I've referenced issue #5256 in the comment...

**Comment by Adam-it** [comment]
@tmaestrini Unfortunately just mentioning the issue is not enough. In order to link an issue to a PR you need to either 
https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue use one of several keywords before the issue like `closes`, `fixes` etc. Or you need to link it manually. 
The second method usually can only be done by a maintainer if no keyword was used and GitHub did not link the PR to an issue automatically.

**Comment by tmaestrini** [comment]
Thank you for your reply. I now saw that I've really forgotten to mention `closes #5256` in the summary. That's my bad.
Sorry for bothering you with this.

**Comment by Adam-it** [comment]
> Thank you for your reply. I now saw that I've really forgotten to mention `closes #5256` in the summary. That's my bad. Sorry for bothering you with this.

no problem

**Pull request merged**
