### PR TITLE
New sample - react-manage-subscriptions

### PR DESCRIPTION
**Pull request by NishkalankBezawada**
- [ ] Bug fix?
- [x] New sample?
- [ ] Related issues: fixes #X, partially #Y, mentioned in #Z
- [ ] Needs API permissions?
- [ ] Has other prerequisites? (E.g. requires a list, document library, etc.)
- Node version used: ```v16.18.1```

## What's in this Pull Request?

This sample web part demonstrates managing the list subscriptions (sharepoint webhooks) and action to renew the webhook expiration date using Rest calls. The webpart is to be added at Hubsite level or the sites associated to the hubsite, on selection of the site, it will list out the lists available. On list/library selection, the available subscriptions is displayed. Depending upon the expiry date of the subscription, 'Renew subscription' action can be performed. The subscription (webhook expiry renewal date) renewal date is set to 179 days, as the default days are 180. 

## Subscription Manager

SubscriptionsDashboard

## Configuring subscription manager webpart

ConfiguringWebpart

## Renewing webhook subscriptions

RenewingSubscriptions

## Configuration error while adding the webpart to Non-Hub related sites 

ConfiguringWebpart-NonHubrelatedSite

## Checklist

- [x] My pull request affects only ONE sample.
- [x] My sample does not build with any warnings
- [x] I have updated the README file.
- [x] My README has at least one static high-resolution screenshot (i.e. not a GIF)
- [x] My README contains complete setup instructions, including pre-requisites and permissions required

## Submitter Guidance

* [Get Subscription](https://learn.microsoft.com/en-us/sharepoint/dev/apis/webhooks/lists/get-subscription)
* [Update Subscription](https://learn.microsoft.com/en-us/sharepoint/dev/apis/webhooks/lists/update-subscription)

Thanks,
Nishkalank Bezawada

### CODE REVIEW

**Comment by hugoabernier** [comment]
Thank you @NishkalankBezawada!

We'd love to schedule a community call demo for this if you'd be interested on showcasing the implementation. Please fill in following form and we'll get you scheduled - https://aka.ms/community/request/demo

Thank you for sharing your sample with others - highly appreciated 👏🥇👩‍💻

**Comment by NishkalankBezawada** [comment]
> Thank you @NishkalankBezawada!
> 
> 
> 
> We'd love to schedule a community call demo for this if you'd be interested on showcasing the implementation. Please fill in following form and we'll get you scheduled - https://aka.ms/community/request/demo
> 
> 
> 
> Thank you for sharing your sample with others - highly appreciated 👏🥇👩‍💻

Hey Hugo,

Sure thing, I would do so.

Regards,
Nishkalank

**Comment by NishkalankBezawada** [comment]
> Thank you @NishkalankBezawada!
> 
> We'd love to schedule a community call demo for this if you'd be interested on showcasing the implementation. Please fill in following form and we'll get you scheduled - https://aka.ms/community/request/demo
> 
> Thank you for sharing your sample with others - highly appreciated 👏🥇👩‍💻

Hey @hugoabernier, 

Thanks for the opportunity to demo this. 

I would definetly like to demo this webpart, but I also wanted to club my another sample extension [Manage list subscriptions](https://github.com/pnp/sp-dev-fx-extensions/pull/922) in the same demo, as both are related to SharePoint webhooks. Do you think that this will be a good Idea? Please suggest. 

Thanks,
Nishkalank Bezawada

**Comment by VesaJuvonen** [comment]
@NishkalankBezawada - Those are both great demos and it works either way - both are indeed showcasing similar story - so maybe they can be combined - but again - they are both really cool samples and if you want - you can for sure do two demos as well - in two different calls - absolutely an option. 

Rather have shorter demo than too much in one slot - there's some cool topics to cover in both for sure... but either way works. I did also see your demo submission coming in, so Luise will soon be reaching out get you scheduled. Looking forward 👏

**Comment by NishkalankBezawada** [comment]
> @NishkalankBezawada - Those are both great demos and it works either way - both are indeed showcasing similar story - so maybe they can be combined - but again - they are both really cool samples and if you want - you can for sure do two demos as well - in two different calls - absolutely an option.
> 
> Rather have shorter demo than too much in one slot - there's some cool topics to cover in both for sure... but either way works. I did also see your demo submission coming in, so Luise will soon be reaching out get you scheduled. Looking forward 👏

Thanks @VesaJuvonen for suggesting. 

I probably would stick to your suggestion, in presenting these in two different demo's, even though it is a similar one, yet can have potential to be covered. I'll be anticipating the invitation. 

Thanks,
Nishkalank Bezawada

**Pull request merged**
