### PR TITLE
New sample: react-graph-webpart-report

### PR DESCRIPTION
**Pull request by a1mery**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| New sample?     | yes                             |

## What's in this Pull Request?
This sample web part shows a report of the web parts used on the current site.

### CODE REVIEW

**Comment by Zerg00s** [comment]
Hi @a1mery , nice sample :)

I just tried it on my tenant. Seems to be working with no issues:

image

**Comment by a1mery** [comment]
Thanks for the feedback @Zerg00s :)

**Comment by hugoabernier** [comment]
Thanks for the cool sample @a1mery (I especially like the use of the chartcontrol, but maybe I'm biased 😉). 

Would you be interested in demoing this web part on the July 13th SPFx community call? You'd have **10-13 minutes** to demo the web part and review the most relevant portions of your code.

Thanks for the review @Zerg00s

**Comment by a1mery** [comment]
Thank you @hugoabernier 
Sure, I'm definitely interested !

Yes, thanks for the chartcontrol, it is really easy to use 👍

**Comment by hugoabernier** [comment]
Perfect! I have you confirmed on the community call agenda. Looking forward to your demo!!!

**Pull request merged**
