### PR TITLE
Adding the react-graph-latest-client sample

### PR DESCRIPTION
**Pull request by sebastienlevert**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                                |
| New feature?    | no                               |
| New sample?     | yes                               |
| Related issues? | none, yet  |

## What's in this Pull Request?

Adding the new react-graph-latest-client sample to promote how to use MGT to get the latest version of the Graph client and leverage the middleware options

### CODE REVIEW

**Comment by hugoabernier** [comment]
Hey @sebastienlevert thanks for this sample. As per some of the comments on Twitter, how would you feel about renaming the sample `react-graph-mgt-middleware` or something like that? I think it is perfectly fine to rename the sample folder and README only, the solution can stay the same name.

Let me know and I can rename the folder when I merge.

**Comment by sebastienlevert** [comment]
What about react-graph-mgt-client? I think it makes more sense as it's more than just the middlewares. Thanks!

**Comment by sebastienlevert** [comment]
Renamed just happened! I settled on `react-graph-mgt-client`

**Comment by hugoabernier** [comment]
Wow, super cool @sebastienlevert! How would you feel about demoing this web part on the May 20th SPFx community call?

**Comment by sebastienlevert** [comment]
Count me in @hugoabernier! Absolutely possible, it'll be fun!

**Pull request merged**
