### PR TITLE
react-pnpjs-spsite-er-diagram sample

### PR DESCRIPTION
**Pull request by ICTNiklasWilhelm**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | no                              |
| New sample?     | yes                             |

## What's in this Pull Request?
A new webpart sample "react-pnpjs-spsite-er-diagram", which displays a SharePoint sites lists in a ER diagram.

### CODE REVIEW

**Comment by hugoabernier** [comment]
Thank you @ICTNiklasWilhelm ! Would you be interested in demoing this sample on the December 15 community call? You'd have 15 minutes to demo the web part and highlights the important parts of your code.

**Comment by ICTNiklasWilhelm** [comment]
Hi Hugo, definitely! That would be pretty cool. Just send me the details (or do I just need to join the call?), and I will prepare a demo :)

From: Hugo Bernier ***@***.***>
Date: Tuesday, 8. November 2022 at 05:21
To: pnp/sp-dev-fx-webparts ***@***.***>
Cc: Niklas Wilhelm ***@***.***>, Mention ***@***.***>
Subject: Re: [pnp/sp-dev-fx-webparts] react-pnpjs-spsite-er-diagram sample (PR #3045)

Thank you @ICTNiklasWilhelm<https://github.com/ICTNiklasWilhelm> ! Would you be interested in demoing this sample on the December 15 community call? You'd have 15 minutes to demo the web part and highlights the important parts of your code.

**Comment by VesaJuvonen** [comment]
@ICTNiklasWilhelm - we would actually have an opening in the 17th of November call already due recent cancellation. Would that work for you. Demo spots are 12-15 min - and it's good to have few slides to explain scenario, showcase the solution and then explain the implementation.

Would the 17th of November already work for you. It's 7 AM PT on Thursday - that's 4 PM Central Europe time. Thx.

FYI @hugoabernier on the potential change here.

**Comment by VesaJuvonen** [comment]
FYI for @hugoabernier - we agreed to reschedule the demo for 17th of Nov with Niklas. Have updated the tracking accordingly. Thx.

**Pull request merged**
