### PR TITLE
Added react-dynamics-crm-api sample

### PR DESCRIPTION
**Pull request by AhmadiRamin**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                              |
| New feature?    | no                             |
| New sample?     | yes                               |

## What's in this Pull Request?

Add a new sample to consume Dynamics CRM api

### CODE REVIEW

**Comment by hugoabernier** [comment]
@AhmadiRamin this is a great sample that I'm sure many people will find useful.

I know that you have a blog post explaining how to get the web part working, but we like to keep the samples "self-contained" in this repository. Could you kindly add some instructions to the `README.md` explaining how to get the sample configured. You can keep the reference to your blog post for "more information".

Also, I've added the telemetry image at the bottom of your `README.md` to help track usage and stats. Don't forget to add it in future PRs.

As soon as you push a commit with basic instructions, I'll merge the PR and update social media/sample request.

Also, I have an open slot on August 27th if you'd like to present this at an upcoming SPFx PnP community call?

**Comment by AhmadiRamin** [comment]
@hugoabernier Thanks Hugo, I will update the README.md and I will push a commit soon.
I'm happy to demo it on August 27th :)

**Comment by hugoabernier** [comment]
@AhmadiRamin you're confirmed for August 27th. Looking forward to your demo!

**Comment by hugoabernier** [comment]
@AhmadiRamin just following up on this. Are you planning on making an additional commit, or do you want to re-submit another PR with instructions?

I'm trying to close PRs in time for this week's SPFx PnP call and I'd love to have your sample in the list of new samples :-)

**Comment by AhmadiRamin** [comment]
Hi @hugoabernier, sorry I thought I need to create a new PR, I updated the README.md :)

**Comment by hugoabernier** [comment]
Thank you @AhmadiRamin. I look forward to your demo on August 27th!

**Comment by hugoabernier** [comment]
@AhmadiRamin there is also an opening on August 13th if you'd prefer to demo then? Let me know.

**Comment by AhmadiRamin** [comment]
Sounds good to me, Iet's do it on August 13th then.

**Comment by hugoabernier** [comment]
Perfect @AhmadiRamin , that way I won't have to wait so long to see your cool demo.  I've got you confirmed on the agenda for August 13th!

**Pull request merged**
