### PR TITLE
Added Sample "react-Caml2Table"

### PR DESCRIPTION
**Pull request by Tanddant**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | no                                |
| New sample?     |  yes                               |
| Related issues? | N/A |

## What's in this Pull Request?

A sample that allows the user to input a CAML query and get the result fast and easy to speed up development time

I've added a simple sample that demonstrates a few concepts every new SPFx developer should learn to master at some point, and also help to test CAML queries easily.

### CODE REVIEW

**Comment by hugoabernier** [comment]
Thank you @Tanddant !  Would you be interested in demoing this web part on the January 26 [Viva Connections and SPFx community call](https://pnp.github.io/#community)?

**Comment by Tanddant** [comment]
Hi @hugoabernier, I would love to, but is there anything in particular that you would want to see more about? - the sample itself is relatively simple, so I'm afraid it wouldn't contribute much.

There might be something to share in regards to
 - PnP Reusable contols
 - React Context
 - What is CAML

But I'm not sure that it'll be adding any real value to those who are joining the calls 😊

**Comment by hugoabernier** [comment]
Hi @Tanddant , there are always new people getting started with SPFx and I'm sure they would benefit from hearing about how you used the PnP controls, React Context, and CAML.

**Comment by Tanddant** [comment]
13 minutes, right? 😊

**Comment by Tanddant** [comment]
@hugoabernier 13 minutes, right?

**Comment by hugoabernier** [comment]
> @hugoabernier 13 minutes, right?

Yes, please!

**Comment by Tanddant** [comment]
@hugoabernier alright, I'll think prepare a quick demo and walkthrough of the concepts 👍

**Comment by hugoabernier** [comment]
Perfect @Tanddant ! You are confirmed on the agenda!

**Pull request merged**
