### PR TITLE
 Added tenant wide extension manager sample

### PR DESCRIPTION
**Pull request by Tanddant**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no           |
| New feature?    | no                                |
| New sample?     | yes                               |
| Related issues? | N/A  |

## What's in this Pull Request?

This is a sample of a "modern tenant wide extension list", I got sick of the "classic" layout, and after watching @VesaJuvonen struggle on a recent community call I figured I would build the solution, and try integrating with the appcatalog at the same time, I couldn't find any samples on  doing that, so it made sense to do!

### CODE REVIEW

**Comment by hugoabernier** [comment]
Thanks for your sample @Tanddant . Can you confirm what version of node you were using to build this sample? I'm running into all sorts of dependency issues building this and I want to make sure our community don't run into the same frustration when using your sample.

**Comment by Tanddant** [comment]
@hugoabernier Should be built using 16.20.0 I will confirm on a clean version later

I recall having some issues with `react-code-editor-editable` I don't recall if I ended up doing an `npm install -force`, I might have :/

**Comment by Tanddant** [comment]
@hugoabernier There you go, I moved to [@uiw/react-textarea-code-editor](https://www.npmjs.com/package/@uiw/react-textarea-code-editor] seems to fix the issue on my end,  can you confirm on your end? 😊

**Comment by hugoabernier** [comment]
Thank you @Tanddant, new version looks great! Much appreciated!

**Comment by VesaJuvonen** [comment]
Going back a bit on history see ensure that we invite everyone who have submitted samples to present in the calls - If you'd be interested on showing this great sample in a public community call, please fill in following form and we'll get you scheduled - https://aka.ms/community/request/demo

Thank you for sharing your sample with others - highly appreciated 👏🥇👩‍💻

and yes @Tanddant - I need this sample for my dev tenants for sure 😏

**Pull request merged**
