### PR TITLE
New sample - react-graph-cascading-managed-metadata

### PR DESCRIPTION
**Pull request by anoopt**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                              |
| New feature?    | no                               |
| New sample?     | yes                               |
| Related issues? | NA |

## What's in this Pull Request?

This PR contains a sample to demonstrate the usage of the recently released Microsoft Graph APIs (Beta) for Taxonomy.

The sample demonstrates how to get the data from the term store, store the data in the browser cache and display the data as cascading dropdowns.

The sample has methods to perform other operations (like write, delete and patch) which can be utilised to extend the functionality if needed. (Thank you Mikael Svenson)

The sample also shows the usage of PnP SPFx map control to display the map of the selected city based on the set co-ordinates.

*Note* - The maps functionality is dependent on the completion of [this PR](https://github.com/pnp/sp-dev-fx-controls-react/pull/641) submitted in PnP SPFx controls repository.

### CODE REVIEW

**Comment by hugoabernier** [comment]
Thank you @anoopt ! would you be interested in demoing this sample on the September 24th SPFx PnP call?

**Comment by anoopt** [comment]
Thank you @hugoabernier . Yes sure, I am happy to demo this on Sep 24th.

**Comment by hugoabernier** [comment]
Thank you @anoopt , I have you confirmed for the 24th of September. Looking forward to your demo!

**Comment by kathyboilek** [comment]
Same here!!

**Pull request merged**
