### PR TITLE
Add Copy Views sample solution

### PR DESCRIPTION
**Pull request by martinlingstuyl**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | no                               |
| New sample?     | yes                               |

## What's in this Pull Request?
This PR adds a sample enabling a user to copy views from one list/library to another across site collections. It can be used as a webpart on a page, or as a ListView Command Set extension.

### CODE REVIEW

**Comment by hugoabernier** [comment]
Hey @martinlingstuyl this is a great sample -- and very useful!

I have made a few tweaks to the rendered HTML for accessibility purposes (only 1 H1 should be on a page at any time), and disabled eslint in the gulpfile.js to resolve compatibility issues with other versions of Node.js.

Would you be interested in demoing this web part on the October 20th SPFx community call? You'd have about 15 minutes to demo the web part and show the relevant portions of your code.

Thanks again for your sample and I look forward to seeing your demo!

**Comment by hugoabernier** [comment]
Hey @martinlingstuyl this is a great sample -- and very useful!

I have made a few tweaks to the rendered HTML for accessibility purposes (only 1 H1 should be on a page at any time), and disabled eslint in the gulpfile.js to resolve compatibility issues with other versions of Node.js.

Would you be interested in demoing this web part on the October 20th SPFx community call? You'd have about 15 minutes to demo the web part and show the relevant portions of your code.

Thanks again for your sample and I look forward to seeing your demo!

**Comment by martinlingstuyl** [comment]
Hi @hugoabernier, 
Of course, I'd like that! Schedule me in.

**Comment by martinlingstuyl** [comment]
> I have made a few tweaks to the rendered HTML for accessibility purposes (only 1 H1 should be on a page at any time), and disabled eslint in the gulpfile.js to resolve compatibility issues with other versions of Node.js.

Also, thanks for the updates! Hadn't noticed the H1 issue.

**Comment by hugoabernier** [comment]
Perfect! We'll see you then!

**Pull request merged**
