### PR TITLE
Create React Poll Webpart

### PR DESCRIPTION
**Pull request by Harsh24491**
Create a new webpart React Poll

> By submitting this pull request, you agree to the [contribution guidelines](https://github.com/pnp/sp-dev-fx-webparts/blob/main/CONTRIBUTING.md)

> If you aren't familiar with how to contribute to open-source repositories using GitHub, or if you find the instructions on this page confusing, [sign up](https://forms.office.com/Pages/ResponsePage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUREZVRDVYUUJLT1VNRDM4SjhGMlpUNzBORy4u) for one of our [Sharing is Caring](https://pnp.github.io/sharing-is-caring/#pnp-sic-events) events. It's completely free, and we'll guide you through the process.

> To submit a pull request with multiple authors, make sure that at least one commit is a co-authored commit by adding a `Co-authored-by:` trailer to the commit's message. E.g.: `Co-authored-by: name <name@example.com>`

> Put an `x` in all the items that apply (`[x]`, no spaces between the `[`, the `x`, and the `]` ), make notes next to any that haven't been addressed.

- [x] New sample
- [ ] Bug fix/update
- [ ] Related issues: fixes #X, partially #Y, mentioned in #Z

## What's in this Pull Request?

> Please describe the changes in this PR. Sample description or details around bugs which are being fixed.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

Node version used:

## Checklist

> This checklist is used to automatically pre-process your pull request; It is meant to help process pull requests in a timely manner, rather than hoops to jump through.
> 
> Put an `x` in all the items that apply (`[x]`, no spaces between the `[`, the `x`, and the `]` ). Make notes next to any that haven't been addressed.

- [x] My pull request affects only ONE sample.
- [x] My sample builds without any warnings
- [x] I have updated the `README.md` file's **Version history**. For new samples, created a new `README.md` file matching [this template](templates/README-template.md)
- [x] My `README.md` has at least one static high-resolution screenshot (i.e. not a GIF) located in the `assets` folder.
- [x] My `README.md` contains complete setup instructions, including pre-requisites and permissions required
- [x] My solution includes a `.nvmrc` file indicating the version of Node.js

### CODE REVIEW

**Comment by hugoabernier** [comment]
Thanks for this sample. Your readme appears to be missing images (and the assets folder).

You also need to fill the PR template (i.e.: complete the checklist).

**Comment by Harsh24491** [comment]
@hugoabernier, Thanks for update.

Added Assets folder.

**Comment by hugoabernier** [comment]
Thanks @Harsh24491 for adding the `assets` folder.

Would you mind making the following changes?
- The Poll Answers list does not appear to provide the Option column, which results in the following error when submitting an answer:
image
- The `Loadder` class has a typo and should be named `Loader`
- The `README.md` should provide step-by-step instructions how to set up the poll. Please do not use images only, but provide text instructions.
- If possible, can you provide an additional preview of the web part that is _not_ animated (as per the [README.md template](https://github.dev/pnp/sp-dev-fx-webparts/blob/main/templates/README-template.md)?

Please note that I already fixed a few typos and added a few linting rules. I would appreciate if you could incorporate your changes in your commit.

**Comment by Harsh24491** [comment]
@hugoabernier added/modified solution as mentioned. For 1st issue, not getting this for new site collection also. Can you please validate again?

**Comment by hugoabernier** [comment]
Thank you for your sample, @Harsh24491!  I'll assume that the issue with provisioning the list is mine.

If haven't done so yet, and you'd be interested on showing this great sample in a public community call, please fill in following form and we'll get you scheduled - [aka.ms/community/request/demo](https://aka.ms/community/request/demo)

Thank you for sharing your sample with others - highly appreciated 👏🥇👩‍💻

**Comment by Harsh24491** [comment]
Thanks @hugoabernier for your guidance. 🙌
Submitted form.

**Pull request merged**
