### PR TITLE
New sample: react-graph-app-secret-expiration: Applications secrets expiration

### PR DESCRIPTION
**Pull request by a1mery**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| New sample?     | yes                               |

## What's in this Pull Request?

This sample web part shows the list of your applications registered in Azure AD along with their associated client secret/certificate expiration date.

### CODE REVIEW

**Comment by a1mery** [comment]
Thanks for the opportunity @hugoabernier !
Unfortunately I'm not available this day. Would it be possible to do it the next time (on the November 11th) ?

**Comment by hugoabernier** [comment]
November 11th is already booked, but we've got an opening for November 18th if it works for you?

**Comment by a1mery** [comment]
Yes, November 18th works for me, thanks ! 👍

**Comment by hugoabernier** [comment]
Perfect @a1mery  I have you confirmed for the 18th

**Pull request merged**
