### PR TITLE
Image editor webpart enhancements

### PR DESCRIPTION
**Pull request by ishaisagi-hns**
- [ ] New sample
- [X] Bug fix/update
- [ ] Related issues: fixes #X, partially #Y, mentioned in #Z

## What's in this Pull Request?

- Changed web part name, 
- added alt text to image in properties, 
- added properties to show\hide edit icon when page is not in edit mode, set default to **off**
- added properties that hide\show the title , set default to **off**
- made aspect lock **on** by default in both crop and resize

## Node Version
Node version used:
v8.17.0

## Checklist

- [X ] My pull request affects only ONE sample.
- [ ] My sample builds without any warnings (some wardnings that are not related to the changes I introduced)
- [X ] I have updated the `README.md` file's **Version history**. For new samples, created a new `README.md` file matching [this template](templates/README-template.md)
- [ ] My `README.md` has at least one static high-resolution screenshot (i.e. not a GIF) located in the `assets` folder.
- [ ] My `README.md` contains complete setup instructions, including pre-requisites and permissions required
- [ ] My solution includes a `.nvmrc` file indicating the version of Node.js

### CODE REVIEW

**Comment by hugoabernier** [comment]
@petkir I'm unable to build this sample. Are you able to build it from a clean install?

**Comment by ishaisagi-hns** [comment]
Hugo, make sure you are on node v8. I'll post tomorrow the gulp version. I had issues setting it up initially.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by petkir** [comment]
@hugoabernier wrong address :-) i have fun with calendar-feed WP Webpack Cors libs they are some years old :-) but I will check it give me some minutes

**Comment by petkir** [comment]
@ishaisagi-hns  
nice enhancement
 lockAspectCrop: true,
 lockAspectResize: true
 
image

@hugoabernier  it's working
only node 8 i had to install and gulp steps are below


steps:
```
nvm install v8
nvm use v8
npm install
npm i gulp@3.9.1 -DE 
npx gulp trust-dev-cert
npx gulp serve  
```


cool thing i learned, a pr can be fetched also as no maintainer :-)
```
 git fetch origin pull/5278/head:testreactimageeditorpr
 ```

**Comment by hugoabernier** [comment]
Thanks @ishaisagi-hns for your update! Always appreciated!.

Thank you for sharing your sample with others - you rock! 👏🥇👩‍💻

**Comment by PopWarner** [comment]
🎉✨ Woohoo! ✨🎉

Thank you @ishaisagi-hns for your awesome contribution to the community with this merged PR! 🚀 You've earned a Credly badge through the Microsoft 365 & Power Platform Recognition Program. 🏅 To receive your badge, please take a moment to opt in to the program. You can learn more and sign up here: https://aka.ms/community/recognition.

Can't wait to see you in the program! 🎊

Cheers,
David Warner 🧡💜

**Pull request merged**
