### PR TITLE
Added New Sample "react-graph-telephonedirectory"

### PR DESCRIPTION
**Pull request by dips365**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| New sample?     | yes                               |

## What's in this Pull Request?

> Demonstrate the solution of telephone directory using SPFx and Microsoft graph. It will be use to fetch the user's contact information like email and phone number from the SharePoint Intranet Page of organization.

### CODE REVIEW

**Comment by dips365** [comment]
@hugoabernier 
Please have a look and let me know if missed anything or needs any change.
Thanks

**Comment by hugoabernier** [comment]
@dips365 from the screenshot it looks like the Search by email is using the wrong font family (compared to the other the tabs), but it looks fantastic. Will do an actual code review tonight and process PR.

Don't worry, I'll make sure your sample is listed in this week's PnP SPFx call 😀

**Comment by dips365** [comment]
@hugoabernier Thanks for bird eye review.
I will happy to more contribution and let me know if needs any improvement. :)

**Comment by hugoabernier** [comment]
Thanks @dips365. How would you like to demo this sample on the August 27th SPFx PnP call?

**Comment by dips365** [comment]
@hugoabernier  Thanks for review this PR.
I would like to demo this sample and 27th August works for me !!
Please let me know if there is any criteria while doing demo like any PPT theme or something.

**Comment by hugoabernier** [comment]
Thanks @dips365, I have confirmed you on the agenda for August 27th. I'll reach out to you directly for details on presentation requirements.

**Pull request merged**
