### PR TITLE
upgrade spfx version on js-display-list to 1.11.00

### PR DESCRIPTION
**Pull request by sharepointknight**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | no                              |
| New sample?     | no                               |
| Related issues? |  |

## What's in this Pull Request?
Upgraded sample js-display-list to SPFX 1.11.00

### CODE REVIEW

**Comment by hugoabernier** [comment]
Thank you @sharepointknight . I've taken the liberty of updating the README and the package/solution version to reflect the changes.

I noticed that the web part wants to render in a tabular format on the local workbench, but stacks the columns in the hosted workbench. Would you mind taking a look to see if perhaps some CSS have changed with the Fluent UI updates that may cause this?

Local:
image

Hosted:
image

**Comment by sharepointknight** [comment]
Yes I'll look at this.
    On Saturday, August 29, 2020, 01:50:49 PM PDT, Hugo Bernier <notifications@github.com> wrote:  
 
 


Thank you @sharepointknight . I've taken the liberty of updating the README and the package/solution version to reflect the changes.

I noticed that the web part wants to render in a tabular format on the local workbench, but stacks the columns in the hosted workbench. Would you mind taking a look to see if perhaps some CSS have changed with the Fluent UI updates that may cause this?

Local:


Hosted:

**Comment by sharepointknight** [comment]
I have found and fixed the issue for the formatting. What is the best way to incorporate the fix into the PR?
Ryan
    On Saturday, August 29, 2020, 08:21:33 PM PDT, Schouten Ryan <ryanttr@yahoo.com> wrote:  
 
  Yes I'll look at this.
    On Saturday, August 29, 2020, 01:50:49 PM PDT, Hugo Bernier <notifications@github.com> wrote:  
 
 


Thank you @sharepointknight . I've taken the liberty of updating the README and the package/solution version to reflect the changes.

I noticed that the web part wants to render in a tabular format on the local workbench, but stacks the columns in the hosted workbench. Would you mind taking a look to see if perhaps some CSS have changed with the Fluent UI updates that may cause this?

Local:


Hosted:

**Comment by hugoabernier** [comment]
@sharepointknight you can continue to add commits to your original pr until it has not been closed, just make sure you pull the changes i has made so we don't overwrite each other's changes.

**Comment by sharepointknight** [comment]
This has been committed to the PR

**Comment by hugoabernier** [comment]
Thanks @sharepointknight, it works perfectly now!

**Pull request merged**
