### PR TITLE
New Sample Web part to edit Application Customizer

### PR DESCRIPTION
**Pull request by kunj-sangani**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| New sample?     | yes                              |

## What's in this Pull Request?

New sample web part named
react-Edit-ApplicationCustomizer to help users to edit the title, JSON, and description for their application customizer

Co-Authored-By: Siddharth Vaghasia <siddh.vaghasia@gmail.com>

### CODE REVIEW

**Comment by hugoabernier** [comment]
Thanks, @kunj-sangani, @siddharth-vaghasia for the new sample! I had a similar solution that I've been meaning to upload, but I think that yours is better!

Would you be interested in demoing it on the SPFx PnP community call on December 3rd?

**Comment by kunj-sangani** [comment]
yes sure @hugoabernier we would like to provide a demo

**Comment by siddharth-vaghasia** [comment]
thanks @hugoabernier - if you have any suggestions, we can work on that... I think @kunj-sangani can demo this.. :)

**Comment by kunj-sangani** [comment]
Hey @hugoabernier we are all set for the demo on December 3rd
Can you please confirm the schedule 

Thanks in advance

**Comment by hugoabernier** [comment]
@kunj-sangani yes, you're confirmed for the December 3 SPFx community call agenda! I look forward to it!

**Pull request merged**
