### PR TITLE
new react-SectionBackground webpart

### PR DESCRIPTION
**Pull request by DonKirkham**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                                |
| New feature?    | yes?                               |
| New sample?     | no?                              |

## What's in this Pull Request?

The project was updated to SPFx 1.11.0 and new web part added.  The new web part uses the themes variant object to set CSS variable, that can be used to style the web part based on the theme and section background chosen.

This new web part is different than the Section-Backgrounds webpart, which uses the theme variant colors in style attributes directly in the "html." This web part shows how to use those same colors directly in the CSS. Consideration was given to combine the web parts from the Section-Background into one project, but I decided to just submit this one new web part. I am willing to do the combination, if requested.

The web part also displays a key-value list with each semantic color name, color code (hex or rgb), and a sample block of the color.

### CODE REVIEW

**Comment by hugoabernier** [comment]
@DonKirkham thanks for submitting this pull request. It seems that your pull request touches many files that are outside of your sample. Can you verify and confirm that you used an up-to-date fork of this repo to create your pull request?

**Comment by DonKirkham** [comment]
I tried to refresh my fork before submitting, but I was afraid I didn’t quite do that correctly.

I could try to recreate it from scratch, as I don’t know how to fix it.

Despite the instructions on updating the fork, it seems like that should not normally be done once the branch has been created.  Maybe the intent is to fresh your fork before branching and not doing it again until after the PR?

Hopefully, this is something covered in the upcoming 2-day “course.”

Don

**Comment by hugoabernier** [comment]
@DonKirkham I'll just extract the changes from your sample and process it that way. 

And yes, the upcoming sharing is caring sessions cover this topic 😀

**Comment by DonKirkham** [comment]
Thanks Hugo! The submission should only include files in the react-themes folders.

Don Kirkham
Probitas Data Solutions
Microsoft Certified Trainer (MCT)
Microsoft Certified Professional Developer(MCPD)
Microsoft Certified: Azure, Microsoft 365, Power Platform
Arlington, TX (GMT-6)
Cell: +1(214) 475-6114 | Office: +1(214) 475-6114
Blog: https://donkirkham.com | Twitter: @DonKirkham<https://twitter.com/DonKirkham>
LinkedIn: https://www.linkedin.com/in/donkirkham/

**Comment by hugoabernier** [comment]
Replaced by #1606

**Pull request closed without merging**
