### PR TITLE
A webpart that allows user to view, add, & edit azure apps.

### PR DESCRIPTION
**Pull request by Diksha-Bhura**
|        Q             |    A  |
| --------------- | ---- |
| New sample   |  yes |

## What's in this Pull Request?

This webpart shows all the azure apps from AAD.
Gives user a functionality to register new app and edit the existing app.

### CODE REVIEW

**Comment by Zerg00s** [comment]
Hi @Diksha-Bhura,

Can you help me with your example, please? 

I am trying your webpart example, but having difficulties setting it up:
What are the prerequisites in order for the SPFx webpart to show something on the screen?  Right now, it's failing with the following error:

```
Error: Insufficient privileges to complete the operation.
    at B.constructErrorFromResponse (ms-graph-v3-bundle_none_a1abe4d2279261092a99.js:2:58343)
    at B.<anonymous> (ms-graph-v3-bundle_none_a1abe4d2279261092a99.js:2:58622)
    at Generator.next (<anonymous>)
    at sp-pages-assembly_en-us_d175a450223b4f83b4f34272c36ea32b.js:2:3772
    at new Promise (<anonymous>)
    at l (sp-pages-assembly_en-us_d175a450223b4f83b4f34272c36ea32b.js:2:3520)
    at B.getError (ms-graph-v3-bundle_none_a1abe4d2279261092a99.js:2:58566)
    at z.<anonymous> (ms-graph-v3-bundle_none_a1abe4d2279261092a99.js:2:62449)
    at Generator.throw (<anonymous>)
    at s (sp-pages-assembly_en-us_d175a450223b4f83b4f34272c36ea32b.js:2:3627)
```

image

image

We are probably missing the `Application.Read.All` and `"User.Read.All` Graph API  permissions in the `package-solution.json` file:

```
{
  "$schema": "https://developer.microsoft.com/json-schemas/spfx-build/package-solution.schema.json",
  "solution": {
    "name": "Azure Apps",
    "id": "2236ddb2-5c5e-4dca-992d-b772027a6d60",
    "version": "1.0.0.1",
    "includeClientSideAssets": true,
    "skipFeatureDeployment": true,
    "isDomainIsolated": false,
    "webApiPermissionRequests": [
      {
        "resource": "Microsoft Graph",
        "scope": "Application.Read.All"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "User.ReadBasic.All"
      }
    ]},
```

Maybe you can add this extra step to the readme.md file? For those who is not familiar with this prerequisite? 😊

image

image

I added these and approved the permissions, but alas it's still failing.

**Comment by Zerg00s** [comment]
Hi @Diksha-Bhura ,

I am using a Communication site's home page:
image

image

There is also a footer enabled:

image
image



I am also checking this webpart today and it does not seem to load anything. Not sure what changed since last time I tried it.
**Update**
it just takes a very long time to load content. I think, we need to wait for at least 60-90 seconds for the apps to appear. But on the second load it's very fast.

**Comment by Diksha-Bhura** [comment]
Hi @Zerg00s,
Yes, it will take some time to load data for the first time.

**Comment by hugoabernier** [comment]
Hi @Diksha-Bhura , am trying to make required changes before approving PR, but seem to not be able to submit them. Is your repo locked?

**Comment by Diksha-Bhura** [comment]
Hi @hugoabernier,
Can you try submitting the changes again?

**Comment by hugoabernier** [comment]
Hi @Diksha-Bhura , I wasn't able to make changes before processing the PR, but I applied them after the PR. Thank you for your sample!

Would you be interested in presenting your web part on the July 6th SPFx Community Call? You'd have 10-13 minutes to demo your web part and show the relevant portions of your code.

**Comment by Diksha-Bhura** [comment]
Hi @hugoabernier,
Thanks and yes, I will be glad to share it with the community.

**Pull request merged**
