### PR TITLE
New sample WebPart OneDrive finder using Microsoft Graph Toolkit

### PR DESCRIPTION
**Pull request by aaclage**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | yes                               |
| New sample?     | yes                              |
| Related issues? | fixes #X, partially #Y, mentioned in #Z |

## What's in this Pull Request?

This sample access drives from OneDrive and navigate between his content using **Graph OneDrive and Site API and [Microsoft Graph Toolkit](https://github.com/microsoftgraph/microsoft-graph-toolkit) react controls "@microsoft/mgt-react**" with the addition of new control **[FileList](https://github.com/microsoftgraph/microsoft-graph-toolkit/blob/f8b8aa81d00bf426b94ee5016d511bc78b36e152/stories/components/fileList.stories.js#L136) "still preview version"** . This new control provides the ability to retrieve the Drive Library with associated Files and folders making easier to develop and navigate between tenant content and access to file. 

**[FileList](https://github.com/microsoftgraph/microsoft-graph-toolkit/blob/f8b8aa81d00bf426b94ee5016d511bc78b36e152/stories/components/fileList.stories.js#L136)** control allow to load files base on graph query's or parameters ids.

### Retrieve Sites with drives associate
image

### Navigate between folders and Breadcrumb
image

For additional revision or corrections please advise for associated 
Best regards, 
AL

### CODE REVIEW

**Comment by hugoabernier** [comment]
No worries at all @aaclage , you can make changes right up to when I merge the pull request. 

Personally,  I have found that there is no better way to find bugs in my code than submitting a pull request. Usually, I find them all *after* i submit my PR.

I'll merge the PR this week. 

Thank you for your contribution!

**Comment by hugoabernier** [comment]
Thank you @aaclage! This is a very cool sample!

Would you be interested in showing your sample in a 10-13 minutes demo on the May 20th SPFx community call?

Also, we'd like to start giving the opportunity for contributors to write blog posts describing their solutions. The blog post would appear at aka.ms/m365pnp/community/blog. Would you be interested in writing such a post?

Feel free to DM me if you need more information.

**Comment by aaclage** [comment]
Hi @hugoabernier 

Yes, I would be interested on both and will contact you by DM. 

Thank you for approving.

**Comment by hugoabernier** [comment]
Perfect! I have you confirmed on the May 20th agenda. I'll keep an eye for your DMs.

**Pull request merged**
